-- =============================================================================
-- Kiambu Road Hub — Demo Seed: HEALTH & WELLNESS
-- =============================================================================
-- Run AFTER 003_seed_reference_data.sql.
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING on all inserts.
-- To remove all demo rows:
--   DELETE FROM businesses WHERE source_note = 'demo-seed-2025';
-- =============================================================================

-- HOSPITALS & CLINICS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('The Nairobi Thindigua Hospital','nairobi-thindigua-hospital',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='hospitals-clinics'),(select id from areas where slug='thindigua'),'Kiambu Road, Thindigua, near Quickmart','Modern 50-bed private hospital on Kiambu Road with A&E, maternity, surgical suites, ICU, pharmacy and diagnostics.','A modern 50-bed private hospital situated along Kiambu Road in Thindigua. Provides a comprehensive range of healthcare services including accident and emergency, maternity, surgical suites, an ICU, pharmacy, radiology, and laboratory.','+254722312000','https://nairobithindigua.co.ke','24 hours','$$$'::price_range,4.3,180,true,true,'verified'::verification_status,'published'::content_status,'https://nairobithindigua.co.ke',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, source_url, published_at)
values ('Avenue Healthcare Ridgeways','avenue-healthcare-ridgeways',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='hospitals-clinics'),(select id from areas where slug='ridgeways'),'Ridgeways Mall, Kiambu Road, Nairobi','Trusted outpatient clinic in Ridgeways Mall offering specialist consultations, minor procedures, and health screening.','Avenue Healthcare operates one of its outpatient clinics within Ridgeways Mall, offering specialist medical consultations, minor surgical procedures, general practice, ante-natal care, and health screening packages.','+254709455000','https://avenuehealthcare.com','Mon–Sat 8:00 AM – 8:00 PM | Sun 9:00 AM – 5:00 PM','$$$'::price_range,4.4,true,true,'verified'::verification_status,'published'::content_status,'https://avenuehealthcare.com',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('Kiambu County Referral Hospital','kiambu-county-referral-hospital',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='hospitals-clinics'),(select id from areas where slug='kiambu-town'),'Hospital Road, Kiambu Town','Main public referral hospital for Kiambu County. Full range of services including surgery, maternity, paediatrics and emergency care.','The principal public referral hospital for Kiambu County, offering a full range of healthcare services including surgery, maternity, paediatrics, medical wards, and 24-hour emergency care.','+254722207070','24 hours','$'::price_range,3.6,450,false,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Runda Family Medical Centre','runda-family-medical',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='hospitals-clinics'),(select id from areas where slug='runda'),'Runda, off Kiambu Road','GP-led family clinic in Runda. Consultations, chronic disease management, travel vaccines, and paediatric care.','A well-established GP-led family medicine clinic in Runda catering to the healthcare needs of the residential community. Services include general consultations, chronic disease management, travel vaccines, ante-natal care, and paediatric check-ups.','+254733123456','Mon–Sat 8:00 AM – 7:00 PM','$$'::price_range,4.2,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- DENTISTS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('Ridgeways Dental Clinic','ridgeways-dental-clinic',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='dentists'),(select id from areas where slug='ridgeways'),'Kiambu Road, Ridgeways','Full-service dental clinic in Ridgeways. Preventive, cosmetic, and restorative dentistry. Implants, orthodontics and teeth whitening.','A full-service dental clinic in Ridgeways offering preventive, cosmetic, and restorative dentistry. Treatments include dental implants, orthodontics, root canals, tooth whitening, crowns, and bridges.','+254722456789','Mon–Fri 8:00 AM – 6:00 PM | Sat 9:00 AM – 4:00 PM','$$'::price_range,4.5,120,true,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Kiambu Smiles Dental','kiambu-smiles-dental',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='dentists'),(select id from areas where slug='kiambu-town'),'Kiambu Town Centre','Affordable dental care in Kiambu Town. Fillings, extractions, scaling and polishing, and family dental health packages.','An accessible and affordable dental clinic serving Kiambu Town. Offers routine fillings, extractions, scaling and polishing, dental X-rays, fluoride treatments, and family dental health packages.','+254711234567','Mon–Sat 8:30 AM – 6:00 PM','$'::price_range,4.1,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- GYMS & FITNESS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Wadi Degla Club Runda','wadi-degla-club-runda',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='gyms-fitness'),(select id from areas where slug='runda'),'Kiambu Road, Runda','Premium multi-sport facility with Olympic-size pool, tennis courts, squash, gym, cycling studio and restaurant.','A premium multi-sport facility on Kiambu Road offering an Olympic-size swimming pool, eight floodlit tennis courts, squash courts, a fully equipped gym, group fitness classes, a cycling studio, yoga, and a restaurant. Membership-based with day-visitor options.','+254709432000','https://wadidegla.com','Daily 5:30 AM – 10:00 PM','$$$'::price_range,4.4,380,true,true,'verified'::verification_status,'published'::content_status,'https://wadidegla.com',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Windsor Fitness Centre','windsor-fitness-centre',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='gyms-fitness'),(select id from areas where slug='ridgeways'),'Windsor Golf Hotel, Kigwa Lane, Ridgeways','Fully equipped gym, heated pool, spa, tennis & squash courts within the iconic Windsor Golf Hotel. Day passes available.','The fitness and wellness facilities at Windsor Golf Hotel & Country Club, offering a fully equipped gym, heated swimming pool, spa treatments, tennis courts, squash courts, and jogging trails. Day passes and membership options available for non-hotel guests.','https://windsorgolfresort.com','Daily 6:00 AM – 9:00 PM','$$$'::price_range,4.3,95,false,true,'verified'::verification_status,'published'::content_status,'https://windsorgolfresort.com',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Pump Iron Gym Thindigua','pump-iron-gym-thindigua',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='gyms-fitness'),(select id from areas where slug='thindigua'),'Kiambu Road, Thindigua','Well-equipped neighbourhood gym in Thindigua. Free weights, cardio machines, personal training, and monthly membership packages.','A well-equipped neighbourhood gym in Thindigua, serving the residential community with free weights, cardio machines, resistance equipment, and personal training services. Flexible daily, weekly, and monthly membership packages at competitive rates.','+254722789012','Mon–Sat 5:30 AM – 9:00 PM | Sun 7:00 AM – 6:00 PM','$'::price_range,4.2,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- PHARMACIES
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, source_url, published_at)
values ('Goodlife Pharmacy Ridgeways Mall','goodlife-pharmacy-ridgeways',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='pharmacies'),(select id from areas where slug='ridgeways'),'Ridgeways Mall, Kiambu Road','Leading pharmacy chain outlet at Ridgeways Mall. Prescription dispensing, OTC medicines, beauty products, and free health checks.','Goodlife Pharmacy at Ridgeways Mall offers a comprehensive range of prescription and over-the-counter medicines, baby care, beauty products, and health supplements. Free blood pressure and blood sugar checks available.','+254709889000','https://goodlifepharmacy.co.ke','Mon–Sun 8:00 AM – 9:00 PM','$$'::price_range,4.3,true,true,'verified'::verification_status,'published'::content_status,'https://goodlifepharmacy.co.ke',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Thindigua Pharmacy & Clinic','thindigua-pharmacy-clinic',(select id from categories where slug='health-wellness'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='health-wellness' and s.slug='pharmacies'),(select id from areas where slug='thindigua'),'Kiambu Road, Thindigua junction','Community pharmacy serving Thindigua with prescription dispensing, OTC drugs, dressing services, and basic lab tests.','A community pharmacy at the Thindigua junction on Kiambu Road. Offers prescription dispensing, over-the-counter medications, wound dressing and minor treatments, pregnancy test kits, and basic lab services.','+254733567890','Mon–Sun 7:00 AM – 10:00 PM','$'::price_range,4.1,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;
