-- =============================================================================
-- Kiambu Road Hub — Demo Seed: EDUCATION & CHILDCARE
-- =============================================================================
-- Run AFTER 003_seed_reference_data.sql.
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING on all inserts.
-- =============================================================================

-- INTERNATIONAL SCHOOLS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Rosslyn Academy','rosslyn-academy',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='international-schools'),(select id from areas where slug='runda'),'Rosslyn Lane, off Kiambu Road, Runda, Nairobi 00621','US-accredited international school (PreK–12). ACSI & Cognia certified. Serving the Nairobi diplomatic and expat community since 1967.','Rosslyn Academy is a US-accredited international Christian school in Runda, off Kiambu Road. Serving the Nairobi diplomatic and expatriate community since 1967, it offers a rigorous US curriculum for PreK through Grade 12. Accredited by ACSI and Cognia. Features excellent sports facilities, arts programs, and a vibrant community of over 25 nationalities.','+254730188000','https://rosslyn.ac.ke','Mon–Fri 7:30 AM – 4:00 PM','$$$$'::price_range,4.5,210,true,true,'verified'::verification_status,'published'::content_status,'https://rosslyn.ac.ke',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Braeburn Gitanga Road','braeburn-gitanga',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='international-schools'),(select id from areas where slug='runda'),'Gitanga Road, off Kiambu Road / Waiyaki Way corridor','British-curriculum international school. IGCSE, A-levels, and BTEC qualifications. Strong arts, sports, and pastoral care.','Braeburn Gitanga Road is part of the well-established Braeburn Group of International Schools. Offers British curriculum from Early Years to A-levels, including IGCSE and BTEC qualifications. Known for outstanding pastoral care, a vibrant arts program, competitive sports, and a diverse community.','+254733612000','https://braeburn.ac.ke','Mon–Fri 7:30 AM – 4:30 PM','$$$$'::price_range,4.4,165,true,true,'verified'::verification_status,'published'::content_status,'https://braeburn.ac.ke',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, source_url, published_at)
values ('Riara Group of Schools Ridgeways','riara-group-ridgeways',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='international-schools'),(select id from areas where slug='ridgeways'),'Kiambu Road, Ridgeways, Nairobi','Kenyan & international curriculum from Early Years to A-levels. IGCSE, KCSE, and CBC tracks. Excellent boarding and day school.','The Riara Group of Schools at Ridgeways offers Kenyan and international curriculum pathways from Early Years through Form 6, including CBC, KCSE, IGCSE, and A-levels. Known for academic excellence, a wide range of co-curricular activities, and strong university placement outcomes.','+254703770000','https://riaragroup.ac.ke','Mon–Fri 7:00 AM – 5:00 PM','$$$'::price_range,4.3,true,true,'verified'::verification_status,'published'::content_status,'https://riaragroup.ac.ke',now())
on conflict (slug) do nothing;

-- SCHOOLS (LOCAL/NATIONAL)
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('Mwangi Primary School Thindigua','mwangi-primary-thindigua',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='schools'),(select id from areas where slug='thindigua'),'Thindigua, off Kiambu Road','Well-regarded public primary school in Thindigua. CBC curriculum, active community involvement, and consistent academic performance.','A well-regarded public primary school in Thindigua offering the CBC from Pre-Primary to Grade 6. Known for active community involvement, consistent academic performance, and a nurturing environment.','+254722345678','Mon–Fri 7:30 AM – 4:00 PM','$'::price_range,4.0,85,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Kiambu High School','kiambu-high-school',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='schools'),(select id from areas where slug='kiambu-town'),'Kiambu Town, Kiambu County','Established national boys boarding school in Kiambu Town. Strong academics and sports. Consistently posts good KCSE results.','One of Kiambu County''s most established national secondary schools, a boys boarding school known for strong KCSE performance, a rich co-curricular tradition, and prominent alumni.','+254720444555','Mon–Fri 7:00 AM – 5:00 PM','$'::price_range,4.2,false,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- KINDERGARTEN & DAY CARE
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('Little Wonders Daycare Ridgeways','little-wonders-daycare-ridgeways',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='kindergarten-daycare'),(select id from areas where slug='ridgeways'),'Kiambu Road, Ridgeways','Warm and stimulating daycare and kindergarten in Ridgeways. Play-based learning, nutritious meals, and flexible drop-off/pick-up.','A warm and stimulating daycare and kindergarten in Ridgeways catering to children from 3 months to 6 years. Play-based learning, structured pre-literacy and numeracy, outdoor play, music, and art. Nutritious meals provided. Flexible drop-off and pick-up hours.','+254722111333','Mon–Fri 6:30 AM – 7:00 PM','$$'::price_range,4.6,75,true,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Runda Tots Nursery','runda-tots-nursery',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='kindergarten-daycare'),(select id from areas where slug='runda'),'Runda Estate, off Kiambu Road','Trusted nursery school in Runda Estate. Secure, green environment for toddlers and pre-schoolers. After-school care available.','A trusted nursery school in the Runda Estate providing a secure, green environment for toddlers and pre-schoolers. Holistic early years curriculum blending CBC pre-primary objectives with Montessori-inspired activities. After-school care until 6 PM.','+254733222444','Mon–Fri 7:00 AM – 6:00 PM','$$'::price_range,4.4,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- COLLEGES & TUITION
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, source_url, published_at)
values ('Kiambu Institute of Science & Technology','kiambu-institute-science-technology',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='colleges-tuition'),(select id from areas where slug='kiambu-town'),'Kiambu Town, Kiambu County','Public technical institute offering TVET diploma and certificate courses in business, ICT, engineering, and hospitality.','Kiambu Institute of Science and Technology (KIST) is a public TVET institution offering diploma and certificate courses in business administration, ICT, civil and electrical engineering, and hospitality management.','+254722566777','https://kist.ac.ke','Mon–Fri 8:00 AM – 5:00 PM','$'::price_range,4.0,true,true,'verified'::verification_status,'published'::content_status,'https://kist.ac.ke',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Ridgeways Tuition Centre','ridgeways-tuition-centre',(select id from categories where slug='education-childcare'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='education-childcare' and s.slug='colleges-tuition'),(select id from areas where slug='ridgeways'),'Kiambu Road, Ridgeways','KCSE, IGCSE, and A-level tuition centre in Ridgeways. Small class sizes, experienced tutors, and strong exam results.','A dedicated exam tuition centre in Ridgeways offering KCSE, IGCSE, and A-level preparation classes. Small class sizes, experienced subject tutors, strong examination results, and holiday intensives available.','+254722888999','Mon–Sat 7:00 AM – 8:00 PM','$$'::price_range,4.3,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;
