-- =============================================================================
-- Kiambu Road Hub — Demo Seed: AUTOMOTIVE
-- =============================================================================
-- Run AFTER 003_seed_reference_data.sql.
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING on all inserts.
-- =============================================================================

-- GARAGES & MECHANICS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('CMC Motors Kiambu Road Service','cmc-motors-kiambu-road',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='garages-mechanics'),(select id from areas where slug='ridgeways'),'Kiambu Road, near Ridgeways','Authorised Ford, Mazda & Ranger Rover service dealer. Genuine parts, trained technicians, and full manufacturer warranty support.','An authorised Ford, Mazda, and Range Rover service and maintenance centre on Kiambu Road. Staffed by factory-trained technicians using genuine OEM parts. Full manufacturer warranty support, electrical diagnostics, body repair, and pre-purchase inspection services.','+254709941000','Mon–Fri 7:30 AM – 5:30 PM | Sat 8:00 AM – 1:00 PM','$$$'::price_range,4.2,165,true,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('DT Dobie Service Centre Nairobi North','dt-dobie-nairobi-north',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='garages-mechanics'),(select id from areas where slug='two-rivers'),'Northern Bypass corridor, Nairobi','Authorised Mercedes-Benz, Mitsubishi & Suzuki service centre. Genuine spares, warranty repairs, and accident body work.','DT Dobie''s Nairobi North service facility provides authorised servicing, warranty repairs, and spare parts supply for Mercedes-Benz, Mitsubishi, and Suzuki vehicles. Equipped with state-of-the-art diagnostics and a dedicated accident repair workshop.','+254709946000','Mon–Fri 7:30 AM – 5:30 PM | Sat 8:00 AM – 12:30 PM','$$$'::price_range,4.0,130,true,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Kiambu Road Auto Garage','kiambu-road-auto-garage',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='garages-mechanics'),(select id from areas where slug='thindigua'),'Kiambu Road, Thindigua junction area','Full-service mechanic workshop at Thindigua. Servicing all makes, engine overhaul, suspension, brakes, and auto electrical.','A full-service mechanic workshop at the Thindigua junction area on Kiambu Road. Services all vehicle makes and models including Toyota, Nissan, Subaru, and European marques. Specialises in engine overhaul, suspension and brake repair, wheel alignment, auto electrical, and spray painting.','+254722567890','Mon–Sat 7:00 AM – 6:30 PM | Sun 8:00 AM – 3:00 PM','$$'::price_range,4.3,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- CAR WASH & VALET
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('Ridgeways Express Car Wash','ridgeways-express-car-wash',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='car-wash-valet'),(select id from areas where slug='ridgeways'),'Kiambu Road, Ridgeways','Busy car wash in Ridgeways. Exterior wash, interior vacuum, engine clean, wax, and express 20-minute service available.','A busy and well-organised car wash in Ridgeways offering exterior washes, interior vacuuming, engine cleaning, waxing, window tinting, and a quick 20-minute express wash for customers in a hurry.','+254711123456','Daily 7:00 AM – 7:00 PM','$'::price_range,4.2,200,true,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('VIP Auto Spa Runda','vip-auto-spa-runda',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='car-wash-valet'),(select id from areas where slug='runda'),'Runda, off Kiambu Road','Premium hand-wash and detailing studio in Runda. Full valet, ceramic coating, paint correction, and leather conditioning.','A premium hand-wash and full-service detailing studio in Runda. Offers full interior and exterior valet, paint correction, ceramic coating application, leather seat conditioning, headlight restoration, and odour elimination treatments.','+254733678901','Mon–Sat 7:30 AM – 7:00 PM | Sun 8:00 AM – 5:00 PM','$$$'::price_range,4.6,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- FUEL STATIONS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('Total Energies Kiambu Road','total-energies-kiambu-road',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='fuel-stations'),(select id from areas where slug='thindigua'),'Kiambu Road, Thindigua area','TotalEnergies petrol station. Fuel, AdBlue, lubricants, car wash, and Total Bonjour convenience store on-site.','A TotalEnergies fuel station on Kiambu Road serving the Thindigua area. Stocks petrol, diesel, and premium Excellium fuels, AdBlue, and TotalEnergies lubricants. Includes an on-site Total Bonjour convenience store and car wash bay.','+254709350000','24 hours','$$'::price_range,4.0,310,false,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Rubis Energy Ridgeways','rubis-energy-ridgeways',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='fuel-stations'),(select id from areas where slug='ridgeways'),'Kiambu Road, Ridgeways','Rubis Energy fuel station in Ridgeways. Petrol and diesel, compressed natural gas (CNG), convenience store, and car wash.','Rubis Energy fuel station on Kiambu Road in Ridgeways. Dispenses petrol, diesel, and compressed natural gas (CNG) for converted vehicles. Includes a small convenience store and forecourt car wash.','+254709780000','24 hours','$$'::price_range,4.1,false,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- SPARE PARTS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Kiambu Road Auto Parts','kiambu-road-auto-parts',(select id from categories where slug='automotive'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='automotive' and s.slug='spare-parts'),(select id from areas where slug='kiambu-town'),'Kiambu Town, opposite bus stage','Wide-ranging auto spares shop in Kiambu Town. Japanese, German, and domestic parts. Walk-in and M-Pesa wholesale pricing.','A wide-ranging auto spares dealer in Kiambu Town stocking genuine and aftermarket parts for Japanese, German, and domestic vehicles. Carries brake pads, filters, belts, bearings, shock absorbers, and body panels. Walk-in retail and bulk wholesale pricing with M-Pesa payments accepted.','+254722890123','Mon–Sat 7:30 AM – 6:30 PM','$'::price_range,4.0,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;
