-- =============================================================================
-- Kiambu Road Hub — Demo Seed: LEISURE & OUTDOORS
-- =============================================================================
-- Run AFTER 003_seed_reference_data.sql.
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING on all inserts.
-- =============================================================================

-- GOLF & COUNTRY CLUBS
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Windsor Golf Hotel & Country Club','windsor-golf-hotel-country-club',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='golf-country-clubs'),(select id from areas where slug='ridgeways'),'Kigwa Lane, off Kiambu Road, Ridgeways','Nairobi''s premier 18-hole golf club, luxury hotel, spa, tennis, pool, and multiple dining outlets in a forested setting.','Windsor Golf Hotel & Country Club is Nairobi''s premier leisure destination off Kiambu Road. Features an 18-hole championship golf course, luxury hotel rooms and suites, a spa, heated swimming pool, tennis courts, squash, a gym, and multiple restaurants and bars set in a stunning forested estate.','+254722203361','https://windsorgolfresort.com','Daily (members & guests)','$$$$'::price_range,4.5,1240,true,true,'verified'::verification_status,'published'::content_status,'https://windsorgolfresort.com',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Kiambu Golf Club','kiambu-golf-club',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='golf-country-clubs'),(select id from areas where slug='kiambu-town'),'Golf Road, Kiambu Town','Established 18-hole golf club in Kiambu Town. Public tee-times welcome, club hire available, colonial-era clubhouse.','Kiambu Golf Club is one of Kenya''s oldest golf clubs, established in the early 20th century and set in the scenic Kiambu highlands. Features an 18-hole grass-green course, a colonial-era clubhouse, a restaurant, and bar. Public tee-times available on weekdays; club hire on request.','+254722111222','https://kiambugolfclub.co.ke','Daily 6:00 AM – 6:00 PM','$$$'::price_range,4.3,320,true,true,'verified'::verification_status,'published'::content_status,'https://kiambugolfclub.co.ke',now())
on conflict (slug) do nothing;

-- PARKS & NATURE
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Karura Forest','karura-forest',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='parks-nature'),(select id from areas where slug='runda'),'Kiambu Road / Limuru Road entrance, Runda','1,000+ acre urban forest adjacent to Kiambu Road. Trails for walking, cycling, and running. Waterfalls, caves, and picnic sites.','Karura Forest is a 1,041-acre indigenous urban forest at the intersection of Kiambu and Limuru Roads. Managed by the Kenya Forest Service and Friends of Karura, it offers well-maintained trails for walking, running, and cycling, a waterfall, caves, picnic sites, and abundant birdlife.','+254722828282','https://karuraforest.org','Daily 6:00 AM – 6:00 PM','$'::price_range,4.7,2800,true,true,'verified'::verification_status,'published'::content_status,'https://karuraforest.org',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('Two Rivers Leisure Park','two-rivers-leisure-park',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='parks-nature'),(select id from areas where slug='two-rivers'),'Two Rivers Mall, Northern Bypass / Limuru Road','Riverside park adjacent to Two Rivers Mall. Walking paths, kids' play area, outdoor events space, and the Athi-Galana riverwalk.','The Two Rivers Leisure Park is an outdoor recreational area alongside Two Rivers Mall, set on the banks of a scenic river. Features walking and jogging paths, a children''s play area, open-air event space, a riverwalk, and weekend markets.','+254709432000','Daily 6:00 AM – 8:00 PM','$'::price_range,4.3,420,true,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- SPORTS & RECREATION
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Wadi Degla Sports Club Runda','wadi-degla-sports-club-runda',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='sports-recreation'),(select id from areas where slug='runda'),'Kiambu Road, Runda','Olympic pool, 8 lit tennis courts, squash, gym, cycling studio, football, volleyball, and kids activities. Day passes welcome.','Wadi Degla Club in Runda is a premium multi-sport complex on Kiambu Road offering an Olympic-size swimming pool, eight floodlit tennis courts, squash courts, a fully equipped gym, spinning and cycling studio, football pitch, volleyball, yoga classes, and a restaurant. Day passes and memberships available.','+254709432000','https://wadidegla.com','Daily 5:30 AM – 10:00 PM','$$$'::price_range,4.5,380,true,true,'verified'::verification_status,'published'::content_status,'https://wadidegla.com',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Thindigua Sports Ground','thindigua-sports-ground',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='sports-recreation'),(select id from areas where slug='thindigua'),'Kiambu Road, Thindigua area','Community football pitch in Thindigua. Weekend leagues, evening 5-a-side hire, and youth coaching programmes.','A community sports ground in Thindigua used for weekend football leagues, evening 5-a-side pitch hire, youth coaching programmes, and local tournaments. Changing rooms and parking available.','+254722345901','Weekdays 5:00 PM – 9:00 PM | Weekends 7:00 AM – 7:00 PM','$'::price_range,3.9,false,false,'unverified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

-- ENTERTAINMENT
insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, website, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, source_url, published_at)
values ('Century Cinemax Two Rivers','century-cinemax-two-rivers',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='entertainment'),(select id from areas where slug='two-rivers'),'Two Rivers Mall, Level 3, Limuru Road / Northern Bypass','Kenya''s leading cinema chain at Two Rivers Mall. IMAX, premium screens, VIP seats, and a full snack bar with licensed bar.','Century Cinemax at Two Rivers Mall is one of Nairobi''s most popular entertainment destinations, featuring multiple screens including an IMAX auditorium, premium Signature and VIP seating options, a full snack bar, and a licensed bar. Screens the latest Hollywood, Bollywood, and local releases.','https://centurycinemax.co.ke','Daily 10:00 AM – 11:00 PM','$$'::price_range,4.4,1560,true,true,'verified'::verification_status,'published'::content_status,'https://centurycinemax.co.ke',now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, google_review_count, featured, verified, verification_status, status, published_at)
values ('The Maze Game Centre Two Rivers','maze-game-centre-two-rivers',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='entertainment'),(select id from areas where slug='two-rivers'),'Two Rivers Mall, Limuru Road / Northern Bypass','Kids and family entertainment zone at Two Rivers. Arcade games, bowling, trampoline park, and indoor playground.','A family entertainment zone at Two Rivers Mall featuring arcade and skill machines, bowling lanes, a trampoline park, a soft-play indoor playground for toddlers, laser tag, and birthday party packages.','+254709100200','Mon–Fri 10:00 AM – 9:00 PM | Sat–Sun 9:00 AM – 10:00 PM','$$'::price_range,4.2,380,false,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;

insert into businesses (name, slug, category_id, subcategory_id, area_id, address_line, short_description, description, phone, opening_hours_text, price_range, google_rating, featured, verified, verification_status, status, published_at)
values ('Ice Skating Rink Two Rivers','ice-skating-rink-two-rivers',(select id from categories where slug='leisure-outdoors'),(select s.id from subcategories s join categories c on s.category_id=c.id where c.slug='leisure-outdoors' and s.slug='entertainment'),(select id from areas where slug='two-rivers'),'Two Rivers Mall, Limuru Road / Northern Bypass','East Africa''s first permanent ice skating rink. Public sessions, private hire, skating lessons, and café rink-side.','East Africa''s first permanent ice skating rink, located inside Two Rivers Mall. Open for public skating sessions, private group hire, birthday parties, corporate events, and skating lessons for beginners. A café operates rink-side.','+254709432001','Daily 10:00 AM – 9:00 PM (last entry 8:00 PM)','$$'::price_range,4.3,true,true,'verified'::verification_status,'published'::content_status,now())
on conflict (slug) do nothing;
