-- =============================================================================
-- Kiambu Road Explorer — Migration 016 (part2of4)
-- Populate business_images with the cover photo each business already had in
-- the original Google Places scrape (dataset_crawler-google-places_2026-07-27).
-- Hotlinks the Google CDN URL directly (no re-hosting) — matched by
-- google_place_id. Skips any business that already has a cover image, and
-- skips businesses with no place-id match (manually-added listings/malls).
-- Split into 4 parts purely to keep each file small; apply in order.
-- Generated by scripts/extract-cover-images.js — re-run that script and
-- reapply if the scrape is ever refreshed.
-- =============================================================================

INSERT INTO business_images (business_id, image_path, is_cover, sort_order, alt_text)
SELECT b.id, v.image_url, true, 0, b.name
FROM businesses b
JOIN (VALUES
  ('ChIJs05YXgAXLxgR01sle3L8t1U', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=JrEdpL8hgGUR9EA6QCsfjA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=340.49973&pitch=0&thumbfov=100'),
  ('ChIJcU9c_-s9LxgRurSHII8e0zQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmRFai1PzMvAj67ffLm0FpUW6aV_Jz0uG1NV3wANH8G5UCZmyHmwExNx8DPCv46SRXCiVv2zcHe2DY_Fb4Zk4tvQ20WXqC0Yoi2T-i73Qcwu43povmCiybs6TZ7sDLDv5TDxxJuyy9w4-o=w408-h272-k-no'),
  ('ChIJd2hWNP09LxgR5n6uCPxZqw4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWme-X-a6fWhHujWMKRnvinddHZshsSzRnAc26c3dUVYqzEnZkx14eP37Q_hmj1rNbQF96_WlsZdQjfJnlgMDmENpFkgOw295SzkFxGuYeTiaiIK9I5AXkGbp_LZjz02dLV_YY3gjQ=w408-h255-k-no'),
  ('ChIJhz-MbgAXLxgRnVv-ly66X8s', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm0c8MoUElXOenQpL14MI6SEtqOLmFr960OMe7c4gse00ZwduygdVMeWWb8Q9Dv6u6Nlj4HfZHVtc6RzY4TDldSvHcydO8pypaU5MKiwN-DDzZhNbXFVEkUxLFs5SzcxXt8vIPk=w408-h544-k-no'),
  ('ChIJX5Mq1Os9LxgRqdhWMiWqsUQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnymrV4SRyt-GCczKTGtZDe_sBxNFAdynvTVrFKxYgbARWYsAFimtisSvg7wQO4A15RzVPAQ0eHIJS-6rn2JJsbmoCa6FJt4mC8a4B1QINChanXS4Famx-un6t1Bfy_zgifjoCID00roizI=w408-h536-k-no'),
  ('ChIJPQngHABBLxgRZkY0ET8JyHQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlv53t9TxLP1xBAgi7wuOpyxrESuf1xZs0IKgO5p-qBJ_7eqsU_jug0r9_rkxRClwiEJvJLxdzN6nUo9XiOqspQQTuSkCYK_emJhzliEKwJ0JNqslyLTopUh9V_8lOTYGVm1ooZDQPlTxOb=w408-h544-k-no'),
  ('ChIJ929C1KsXLxgRURH5JR4VxO4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn5I9YeXxxGmvXl0XyrX6kMIYrgteeJ8h53CO_tFK54lSP98H60fPrqcuHlikGGZozAtSRv5NF16zIejV9sd5eUqEcXIpXwLG79GexnSCYyGlIsssWc5zBHN1MenfDZsKfb47aFgg=w408-h544-k-no'),
  ('ChIJHWIxFWA9LxgRWjEAKTqK7rc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm_VIfFRMwBomhdZX1aFDZqjs7rvk1qXb6fLFSUynm2_zXv2ohcmSLAMqgVE6iM14iQ6SFBeyBJc13vmaLDt654vzVOQAqN0LX2VuMUyMD2gYOOmmAScCz2V3gU_Ft0i6m5mJkjVw=w408-h544-k-no'),
  ('ChIJ3ZQpY9o9LxgR504IJMOGHq8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlVzqFAiuMn-Z6Yawmz-XxbKE9Ku5uJ3JQWVozkThDMHu7FCmN2bswrbzvM0phYBxZDOh5Ufrb52YklMOAHM3oIYxNDj_FhPKog_2vvYy4QqkdCg8dupVqk5PhjEBESvcnvRYHo=w426-h240-k-no'),
  ('ChIJs-vQcAA9LxgR6YIaXqpnr24', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl122PT1Z99d6OWklW6zLIBiiwKy4XejRtPRhjjsU6DN26a_WBdrrkbxP8EYMU3g8qznuoC16iRNZ-uzATtEzoiqEinxnp295_bchEt3ZKXVmqIv6hKlc8G1d5decJyea2F0nqQC9sgNPE=w408-h306-k-no'),
  ('ChIJRSLAfJRBLxgRXNJxDz7pj1s', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkXkHV2h11NaYxOdfsg3_tktuHtTUXDhFqT9FlPU82_5d2hHpFJYu55LvXD3qKbJKhQ5duzBWTkwcOIbZef70Ot5lLWdKxXUiMx-POzn2akZwincOiTl4LhAvOXcjaiPzTZMfUiiPRbV1N0=w426-h240-k-no'),
  ('ChIJ579hdUsRLxgR1-Rz_Gine9s', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=nMOdXhfcu49gUtvaG-XSmQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=57.675987&pitch=0&thumbfov=100'),
  ('ChIJ1U5FX6AXLxgRK1Iv7MDN-9k', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmlNvNWFNLkUce8BeaJ7T5LrkBl8Rw863GM1YZpI5-pU-tOL76KnQ58DPD1YGQniDnN_Eg-wZB0n0rbaCrZ9AcYy1I1lvI4VgAho-5oQ9D5sI3Q4wmv3F7YtpRI8uFALk-GhFhesdLC1Kw=w426-h240-k-no'),
  ('ChIJ-8Y_B6QXLxgRU6MzLT5EtH4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlYxwu80yVWXAJyh0z3gi9BviGvENyzS6aei9XAZ_4zWPvmFe99G81f6IeI_IiNYmXgxk81BvqsyX_83CutQKXcD9cRxWr57FEDDPzmjF2DqPmuOGAPlRuJeXnV2-gjuJ0IPeATVDJBOlM=w532-h240-k-no'),
  ('ChIJ4zxbEQI9LxgRNEGHuPlMQ3Q', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkPduH6ms2fFwskFcB6X6HZkoS4ZzrTsgD9uPyo-NMVb6ZGAOEm9kbNzUYt7xL8e_ZbKENQrnnV7Dsl322Pxl-SdomkrS7f6xXK_IvCZbMzzfaffAjOwfg_4f3B8e3Lxi3VmWwp=w408-h244-k-no'),
  ('ChIJn-s_C2Y9LxgRRAMljlfjH7U', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk0E6Hi7oKQlSdv-Z0aRDgMlSPqhjyf40ADTHAf0aGe4FhVbZWh-jPfw6HLua9Z7371isvA0CvlJT7fxFaIFsyz_pywRPVVGq-drhqCn-AtDcN1UyfU0Kjularj9tUG8jM7oq6FGA=w408-h306-k-no'),
  ('ChIJi9Ku0T49LxgReZG2QWtm19s', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlls5RiGBo9g29EbY6V_hoL6NfFkPb2TcOpYAYdGAc2KN1jBmu5pyRCcLivtFDZQDi8Ir2a-WEa09QGP6cCJj-4mzyxOP6djwT-yRSgr0Lo8582_nNenrtmnxuqlf0O3aQxD8pIIaYBAl8y=w408-h416-k-no'),
  ('ChIJzwK0K489LxgRJJMDxYvnHFM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkuBwYV0GT_ES6-Gi8Fgsyhx3aOeDItmLWFHSBbsXAYJNs54EQjWAnvTtludiZ9nK9jTcbT1-sfABupG4ysMuRV_lwDxSbeJx2AkIFKAmwm-gdhcu5MHG7__cw9DpOpi90qVfAm4A=w426-h240-k-no'),
  ('ChIJB9Qq-hQXLxgRROYVJ247GWQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkz0fyEI0Oi-qjEncD-mzYhvLcdOGjWIBFCtC5mFNhDdov8xGryllFGResQD2T_NnwTBQuAS0PjdGFtAYtbI61n9PSQHN_XWPNvQkoBeqg9vG81wIrCJoohhauqpTDoqafJyvwT=w408-h544-k-no'),
  ('ChIJ406EZt49LxgRofE9xrF0xQk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkFDGRDdsfB-cgbJXMP1I7l06Ly6Fn7ad29WP-wxu7XkGPoudUOySvxihDJ0nqqrFxDZNJfdA1IV7e-iwzRtlSG1znIwnkek3gmC0dAFv_eWDwddt8q4fJ-YKZ74ghUI4MMcV4zqQ=w425-h240-k-no'),
  ('ChIJgwceKfA9LxgR4aIYicpglqw', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmJFNW5vS7YtNxGb4eGisEsC96a2KmXVTSLRYfbn-8Z-Z_lKYyJ1puwDX7XKDC8aFbg5kEcXRGL8XLEHWfUc5fYgKT6cC6No91T6Rkpn9n9NE5L_EN7j6cuD673W2WrGb1-i5-B=w408-h272-k-no'),
  ('ChIJRafshCY9LxgR3kIWD5TCJ8A', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlLuqH2HGWRsrUDtKVm1WnTrUWQgdvmR1m8QjMlJEBFMWhDwgPmhbphgITiyQ0g_txLhlwC30sYnlI2tFcv9r_oSew3fvMgE4gAPadCwt_0ScFHZSJC1uMkQ7oRwlJJGtvRNww6fo_ZPBsi=w408-h272-k-no'),
  ('ChIJC1PCuSw9LxgRYNqTrOQt6Ak', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm3bCTkBPJ5hPDzPEpsjIzokYEafFTqrXNlsuGUzphuozKB8VUKnFZEyPVI9O6bMy8BMXTFOHBrxmShB8fsCQ2NCkBBVvhtSWoEaCJs10ofmSxovnsxYjsUbf7fLLmAILBcuWUb3w=w408-h544-k-no'),
  ('ChIJ8VUleiAXLxgRC4BWbLO4zuM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm0_AF6lTyaU5ilL2FMOH40h3knVvU2hNsivf2x4c4_XbwIXw2jZNMf5AL7XzLIPqRj9ox-5g1tAMNoL1e1dTJvntFiiYOFDUtKHX1uTfoQfm9BswXJ33lAl3bJgrIpnNEoYzABO-7O_H7u=w408-h544-k-no'),
  ('ChIJu30U_Wo9LxgR7V0pHZMrEag', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkaUWUzOA32dZzF8jGeXmfQR_OiLfZU4B-4vRSFOBxiF383un3tG7E8uJ6z3uh4ppfla9I3WttOuyfGmqcrVn-72-o8x5T8LJ0k6zlhQIab9GO-OT0ZBi3MQazbuQs26MNhlp9p=w408-h408-k-no'),
  ('ChIJryFimeE9LxgRwqtshdYfWwg', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlLzqrByYjPrTXE6u6KVMdimlA8PlvLJdmvZJbe9RtuRWpR-l27pdQ0HPyUpqLmQKA3-0Mv1UkVn262vsdfcSaT9uVTetQyv04JyD_dlqrwaMI8TX1UOkk5RjQCefOUCcAGuFi2qwJ9K-nP=w408-h725-k-no'),
  ('ChIJNS89r0I9LxgRd5-qzyrA8PA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlUVZ6ozLEOIVC2TyqB_-_rLzdLIFFET2tkup636qwUn3mPqnwDEOVSEkxeI1n9lyCVvDAE6XcFXlsKk05hMK7sDPwbJGnxzrN-3Pzs5TOJLjKs4i02fsaLEFzK2xkXMRGUbI1fEwoJSpgi=w408-h725-k-no'),
  ('ChIJxTzTe-s9LxgRycu4vKLjkBo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlQNAjNPq1sdCy7YLwhig6amtUmzg4bhIZq7udaWnW7acYAR2lc9fj1ss65AwGXpPsaAJZYzcmVY-giBth1xSppq6kZEZb_pzzPrQxi4hEUGJbP-YstR4FtgtBbNRsljasxlpuC=w408-h408-k-no'),
  ('ChIJgTB32Rk9LxgRoIMkxXf8pq0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlwAVYEdz6wmacmezhgjEiP8hiBRc-NEuety0WxBa-l1sUPX187jVeGdoLetvp88nZlusVAsOQMb1i7RZ1JkodJ6W_s0b2q8BM30WHXxlqoRWnLFyPFlXwj5Bf9s3DW2hAR7cLO4g=w408-h306-k-no'),
  ('ChIJmfibDeg9LxgRp-rrhjFpitQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmImNuXYjWRXO7ctITlAJDr1gVY8LWnB_oqpfdocaGSvdDE0kYMCjqA4ZjJxBkIzVUtnZbduo4xrASb-32NHZ4IYUckJ1FriglP7r__awrG6QtDkhruUeAwtIyWeu_AaPR2BVnUFLfbzuGK=w408-h544-k-no'),
  ('ChIJA33esbgXLxgRsrth7ccAROc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlWOeDL84zz3bMDdk2BZat4T3bjcuP8yfFNbF1-KvHmdYF4lqJBhkocUrWxiItxAFsGFoBNrDyrJf7XOt6tRbUVbZUZotEzSxluGuZV8mmpExzOwkOpCKVlkbni3U1x9w65NDxBY4SUD2CW=w408-h544-k-no'),
  ('ChIJFQmtPbERLxgRt2nC_HswBrQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmTu8KTz-AtI7DpeRP6JCQ8vLiyRGjLWwPgVeo2sCSYigpxA7sW8W0ZHomlCZbhQ2gREwIwmC4XmVrgPue95rTACXVbx84ho3aMnlRbB3GVx3dube114Qhna-CMvCvVhW_-kiMh=w408-h306-k-no'),
  ('ChIJge0Pd9o9LxgRjvwyWaXxn-M', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=fxguImkVVdr-pJQgLYqgPg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=65.38261&pitch=0&thumbfov=100'),
  ('ChIJsYM3iLQ9LxgR6KM7wyzCjlw', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnTIvX2t4gtcykatD2EJ38RMhiOGCnTJ_hRdbpBwAHfO_zLHzKFTkFXwzFbL78J9oJ3CQaPdcOLmC0FxKTXfs5LkbO9D_NDdmXmjzPMa8iZOU0X-phIqMVquu3-PhY58J6hI8CI=w426-h240-k-no'),
  ('ChIJ9cloUgAXLxgRYVNggVRwibc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkU1SkIgVZSCiNJDu5aKUCog_NXtRu6wf6GPGx6q1PrrJgfz1pmM_LxzainqCXnA_iOGXRsf9XJs7I-Pop7Ibj5Om5xy3_99U5wYglgzay7-IKEGNrokm6ohlf73nYKZISu--R-TQ=w408-h510-k-no'),
  ('ChIJJ8IxGAA9LxgRZaXuRT04fVY', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=fxguImkVVdr-pJQgLYqgPg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=66.58812&pitch=0&thumbfov=100'),
  ('ChIJ07KMBAA9LxgR_CU5U8PSLjY', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn3LliLl6x13we-E9NdDXJT1yyyNt93c05Bzt28KfSbq7edVmtC0AIuN4CBSKsFhGGfQa77DWOVniFS9DcaJNagj9iXJ3Lpq1bUkGAIRfiHPARtxyTUWsF3arvMFJReYt3FUTaLn0UcnUtl=w408-h271-k-no'),
  ('ChIJ0yNDGYA_LxgROVBEkN5NR_4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlCzFBNu0tL05YBMViMoIjUqcIlFkMzaVGZt4cMBS-0w8JI7P3K022Ac3jYvzpddzb7yVTQd089Omke8TDPT_B5ruY6c4GfOoNj-fAuPHh3l5biHZv9o6sXI4kvC5SJnotIQ7oyT6bvJQ1r=w408-h408-k-no'),
  ('ChIJf6PjMQAXLxgRbbM-6xH6Xl8', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=oBaxp94Ji9v67veDrrNF_w&cb_client=search.gws-prod.gps&w=408&h=240&yaw=6.9506793&pitch=0&thumbfov=100'),
  ('ChIJe02UTAAXLxgRLAmAQMRLeLk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlRv6wAHEFOfiXXELUJvCWXF8rVryb9PRFFut0WCrJ-Lztw3hkZ0CMJ4rkhZZhIUI7L3RLOVAO0lKmbUQAtnsXzpYdhQ0paSRMqWp6C-koXnvH_AvuTZydMCgL89AXxGGJ49Gm1=w408-h910-k-no'),
  ('ChIJNzRlOF89LxgRWvYtX7W0gpM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkXFuMi4N8PXQYcx9ap9P2w4z7_L8r3mc3iscTlS7QfLtdCjwnOat0xWEsf6cUbu1-oCUwwTJUp-YTpiuEg5q6aa3IJQ5wSTAXTudSyTLSwIX5u7wN7v9R4AHxkDrZDRPYwuE4V=w408-h271-k-no'),
  ('ChIJQ6wOCX89LxgRxm5VSlUIdCo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnvsraZ1zuZi8q98Ei-BsRDCwZZWu20_eBeMZXkBFYhnSZ9tuSdxy8HwCPLj9irOc1R2Zod4-6frkBtHsPJCDy0uvLz-vOuFtgpPJbMswnrevgm_bOPq4etsrYiYQMk2wBcjoXy=w408-h326-k-no'),
  ('ChIJzV_rT-U9LxgRrJ3Wa2WeYp0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl0mC9JaTBvMBjG2n382qUIGD_mAQIyXjKXHcJFN54TLsrxNwD6duej5S649kIToZQ4GZPclsqUhZvGDtu1lhha4C6lELeMVvHZbO6YtDXyUzcSy3Op3p-UAap9AuNoiN_vnWFoyw=w408-h254-k-no'),
  ('ChIJEW5XSAAXLxgRxu_hkmVr66M', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmIJkaQuBz3-eOF6Tirt_TIKJIdxXq5Mb1AzI8x03kpm9woI_8QKhVHMLc-2Jo7Cc_vT6aDffCtKPfw5fXaGwjlhy9m37rDJ-ZFSk3XIP9VRRVHwQV_r8A8qASgo0GyMuVd8vH_7gmt_0bC=w408-h544-k-no'),
  ('ChIJAV2kEwAXLxgRv-N9SqcQBRc', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=wqLSkvrbrFTyz_zc08BBfg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=281.3188&pitch=0&thumbfov=100'),
  ('ChIJA5C26kI9LxgRYlaPoqmtEq4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkjnSS_djT3PqLN4zN6psaoKxWKNNkRqigL7EKXjm83RSnFNL0KWw2gIfKFV2uk6pFts_1ICMGdiHbq3OVCdxH8IE6Ya4EyrwXJvWqx_q5OlBm02yuXQSQaOV8Z1FEPKNJIoFAolg=w408-h272-k-no'),
  ('ChIJE2_qeIc9LxgR9BmPPPgAk4k', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=fYbVQ7lEUG0na7vsqeNzvg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=180.92552&pitch=0&thumbfov=100'),
  ('ChIJ3RzoPL89LxgRMiwanFvjXaw', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnFCVPWhibVfoA1qaQ3NI0JJMhhp9VGq46U3ivH_fPAGfP5XB65Pt8lM-bE8g-7lukMoM31miraxo89K5hvy8d42mv0wQWC3G7cmEded8iJ7rnnwu7c7HcAwo5qA6FveCI9eoQ=w408-h908-k-no'),
  ('ChIJeb618_U9LxgRWuaK8mTUzdI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnZHtJUZPFPHkyp8v2lHx4O57SWDDjoFw9GXBDUWNSziPIq3goPwjRjHtvCFBHzw6xnHLABGCWb7Mh0BXiWw1eoSR41nD_CVSw7rGvR11esZo4xhmmWemlYj8fwR1UwcPlSU4mB=w408-h272-k-no'),
  ('ChIJsQ4QfgA9LxgRXP0-Fn3INcA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmIfXopj5ZP8gjtDj3Anp4C-Avq2GXu1CbmiPnjP7ZWikKygZfqwUoMaonL3cA9lK6aMW_EtqMJRmXDRR5TiWdvr6elcrAQY_LTHmZdKMYYqHirl9WmvpFrW5dmKUuhuG4He1y7QQ=w426-h240-k-no'),
  ('ChIJt5lEortPLxgRxUdnUk2jo9o', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmz847ljin9ssfhmjxbgSfaT-CHP8F4mf1rXk0U9_fHdCcgj4B4rD9lLbQ9dpzBWOArBwCeAFuPAPRa4UB5Hi2xf1iBPuQ4gl3JPQSid6V3kiuz6s1eEGRHZcd2uRcign-9_ChK=w408-h306-k-no'),
  ('ChIJ6635byUWLxgRfLCIV7WSLDM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmVfMeIWRZg14UaAw6N7_tZS3eo7mQgRkofcMiALdossxnUcbW2u0zXYjURYBZfNMcOXMOO0g8ByERcUVnffEbWjEc6P2wSCHSHHoq1rOYpRf9eTaQOKBg59j6E9abYs87Nlc8=w408-h306-k-no'),
  ('ChIJHfDHowY9LxgR9CVrqTlSMm4', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=7Ft_JJiOFD_H9-vhAyCXnQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=277.50638&pitch=0&thumbfov=100'),
  ('ChIJZ7vYpNQXLxgRpyy2ZuOWEnY', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnN5QIfMVFO2HykGklIS-9AiR-slxi2aRKRAkmM5X38CfxP42nWJUj8wLT9EsRMa5_f9jxx-sJgNnQihj2TIR3WuLhfVj2VndYHbKvP2EE025sm7WVTXwweJlRzO_sjn0gHPPjF=w408-h272-k-no'),
  ('ChIJP_CHrigWLxgRRAvRsI8lpSA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk8PWgAPk2SaTkAxleJwmTyU-GqjkeViLb-pNs9cycPevnKFh3bvHp2f6IvDQ_U0yhiCQC2wEuftyqQ5HUAAwfUuO3mvdT36TKY2DhWiCFK-UEYfdFhhJsXXgQCxHSOx_9Wk7z5=w426-h240-k-no'),
  ('ChIJpW-gyqgXLxgRXBrdEnFHreE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkC1A2VHZ4hHAH--VJpSHp8tUdAAZ3abHB0Y8BMBDchIJjSmKvDGv3Eb3SzP_DHeX0fjqI_SxO_k3YDYwNAMMY_1WqliT0KDESzUQip_fDjpaU2OMfu8djkcL48gJCh7-w0-99QkK6sB2Q=w408-h272-k-no'),
  ('ChIJQdgNbwAXLxgR8W3gAnxnhuQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlTjPcpmfg2G1xdySIdQwKJEnynRyIsI99llX5Pf_2KFEo1W7MLl6s1sQtXg4n4V7k9LF7-aY5ElY5Hdlb3Be5cJ-HuAheMkd3PP51H-iH5sqK-WrTW0_bGhRxUq2dzq5vJz-Y9vQ=w408-h306-k-no'),
  ('ChIJt4OOQQE9LxgR6cBaMJ53bKA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnI0zlBs1SNSnVOoihTjN5QkMWvu7WN0tU3FiyN7Fr33YZ2s3ZMNog0L6VAHL5FBFj3C5G3H1Gj-MVLQ36NJ7MvmbaRqByfQTUK8P7bOYDBnwrPoNp_vHHdSSrsjG9Kx5pjPwwU=w408-h306-k-no'),
  ('ChIJX63smNAXLxgRDrNdQGbDGmY', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlxKyxmT_AOV2wf3qj6R6OxtjgIqeSbfTkfzwVdzj29StqNVAxNR8-pF8GdgPTWIgLJYU8ed6y6yoTZReVPgCbgJ0d0lQgQ6Hrbx0bItElG4uwbs9jNP7f6nRbzWxWIFU3By7IcB3XCdSP9=w408-h271-k-no'),
  ('ChIJGUIwPtw9LxgRezhqGQw6b9o', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnUFTofws40orKU7CiUJkx6ronuu7hpN7HrxLUn9k3w8YGyrE-AYFHMjFFmnAjGAY2xIQJA7m_c_hf-5F8wj8c4l5rKh3SX6tpLDWuBDtUChcEQ7T6gMOO7fkGs6qm0z-J11qbp=w408-h306-k-no'),
  ('ChIJpdQVzCYRLxgRuaymYl4ZG08', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmV95K0gzYuwRmBfce1SGu91_aF34QkhO7UOH5znygIlyIVXmGblsFyWOqFwjOfHnrfM1BKJQ5s4fDxT7V9LUgSPa_vzJ4rXQ2Z8KtJTP7oWWgJjA6Vvypx5RDSdRQYI4wVGn2bKA=w408-h306-k-no'),
  ('ChIJIZSzLi09LxgRGX_BmIDVu9g', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=9ilSf8ugZFypX1Bidyb2-w&cb_client=search.gws-prod.gps&w=408&h=240&yaw=294.42084&pitch=0&thumbfov=100'),
  ('ChIJt8ds1go9LxgRUWeJ-kqWgy8', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJA7SDuoM9LxgRLxYlKDr94EY', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWng0KpJ_aTixHb2fbgaky4edH3Js354FktLEjm2OfQBknbaq6djcnckwmtK8fQU4yiWXSnaPoc1I0vOsJpJq5rebMs56DL-MHW6T1nF4l4KEVmcvwD64vgjdnUgAEpTp3QV4nntXg=w408-h306-k-no'),
  ('ChIJAU1GK8I9LxgRHjsBtbSL7dI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk-_o7IOe06JHrMo29cO0sGj2aMjAERNEWop8xjfVb02tlxB3qIhqQujiZPiFUzHNNwzk3BT-ZsbAf1I5RWD8ma5a_e9rVGn6gG87Ea1peBjUsUdFF_-vbEkGifmqhfyD6kJppLig=w408-h242-k-no'),
  ('ChIJR71_4ocXLxgRvQAG7-VhgHk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkjQ8r6HhDKcEzWMuzgxVQHbTgc2TWdbokrkZuBiNav7KX0piZxhyrC4FQn-4FQp6cDRjNsh6QXedbFAcLM43dF9hotFJ0u5_nbYPTYeQMPmrwGkDyZKmIOPvMYuaLvKh3Act3H4w=w408-h306-k-no'),
  ('ChIJTYlNu7ERLxgR47Gs2avHhMQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnQAyQD3WUn7b1uyGvMco1cLikvFCv34jefVnHcM79j3JHezCym4RYp_nUf-klORnSts7McV1PdS1-XVoOSR9SC5J0x1MayNsy9xGGIZ8DVdzhU0uU4DUVSq4RoB1LtJgCD9SNp=w408-h408-k-no'),
  ('ChIJifscWZsXLxgR4MLwXxYiocI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm21zY-r0bhbvaC_4oV_us9Unz9qw-0E6gXQVQIb9ue-YfNLG97i_MCXV2C98wQ0D0oZwhQjpe0uh6BCRZ-ZjUzNjA9vuk4sAKtMfiEnk-xK9dRAhb4LN7X7RWIPEtd9P3gLRCwww=w408-h306-k-no'),
  ('ChIJ40F7z4c9LxgRcJiExKpH338', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=jqlnEfakdD9dOOBZ3wpL_g&cb_client=search.gws-prod.gps&w=408&h=240&yaw=197.97983&pitch=0&thumbfov=100'),
  ('ChIJ4ZPNZF4XLxgRfUgDWakMZc0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkXu2qO5JL4vqAypwFBWf9aXrJyHJNKp2d31ekL8EGFdwBiALjeZr6VMjqKowa-MKWET2Dw7qVYQpXfkk0wxqc3tRqaew4urYKK_bzoUDf8u6YBP0oBUYY3xebcKK5D4q0DC43cza5yEVb6=w408-h306-k-no')
) AS v(place_id, image_url) ON b.google_place_id = v.place_id
WHERE NOT EXISTS (
  SELECT 1 FROM business_images bi WHERE bi.business_id = b.id AND bi.is_cover = true
);
