-- =============================================================================
-- Kiambu Road Explorer — Migration 016 (part4of4)
-- Populate business_images with the cover photo each business already had in
-- the original Google Places scrape (dataset_crawler-google-places_2026-07-27).
-- Hotlinks the Google CDN URL directly (no re-hosting) — matched by
-- google_place_id. Skips any business that already has a cover image, and
-- skips businesses with no place-id match (manually-added listings/malls).
-- Split into 4 parts purely to keep each file small; apply in order.
-- Generated by scripts/extract-cover-images.js — re-run that script and
-- reapply if the scrape is ever refreshed.
-- =============================================================================

INSERT INTO business_images (business_id, image_path, is_cover, sort_order, alt_text)
SELECT b.id, v.image_url, true, 0, b.name
FROM businesses b
JOIN (VALUES
  ('ChIJk4efcZE9LxgROj6OHPC7gSM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlhR1M1vJJy0CTNGgo-Qwi9gFWmZ_Z8cIN-aCHmWSPCa8SzPk7Djt3YunvoICRhhIm7ahx_oTZp_XLX44aMZWLtNuGO-CDW13Tf-ybgtjNGLIvFOCp2OvqfEgPBHvV4bpaNBJTrA7Nl_yVS=w408-h457-k-no'),
  ('ChIJz4Ci3oQ9LxgRWJobAaBheT4', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=v4QWjxL0fFfNQ9nM_PZhtA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=263.18402&pitch=0&thumbfov=100'),
  ('ChIJ_5gA2oQ9LxgRANwk7sKUI7s', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=RWcrUTBHVPsucNbP94im6g&cb_client=search.gws-prod.gps&w=408&h=240&yaw=265.51605&pitch=0&thumbfov=100'),
  ('ChIJiR6kD4U9LxgR1O760o-KKQE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkxfUYI5MLkResAJRVZYOShpiTyhpi2VycNFYorhCrBcFtW7PBEsZXa6J97YVsGSMfjfde3z73_b4Di-GCfJybUqBD0HRx7d2HGjDqV51RfhLoBrQPWs_RQlQCW8ZeA8j5XbX7H=w408-h306-k-no'),
  ('ChIJO6RBL6s9LxgRrxKh5K-p46s', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlNGnouXSrhf7bgFdoqCF9Z-iUnbA-vaG6PDfPhELGx3sp-Ta1uy0zeO20YmXjf1zJ4cco5vHrrl9YU3G6ISYetRlMN7ZPI_76bJ2iZLTi0u6nb34ru7fAGmSAgc8_Sh-cqj6FY5A=w408-h544-k-no'),
  ('ChIJT0TNVYQ9LxgRLJ7qQxNs7Vw', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=r03T2mbvLG0fnpqeZSGskQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=250.75403&pitch=0&thumbfov=100'),
  ('ChIJt8Zzhn49LxgRb3i_sahR2VU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlG5Xriw3YgAcibSm7oDP_ga3xKLCn_ConT9c-qtJlrNR72IIhbxeiItfMRZT40-tk_4TwRfMH_67fp8iPtLK8CONSNSnwDJrbUXo72XPK3n_tPbVquJzoOeXd-WUoZg9bNdTRFw9qpyeY=w408-h544-k-no'),
  ('ChIJuRNv3V0VLxgR0qGRILLkm5Q', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnM2CfXdk1_6rIHwjcipjBJynVqtXtE4vmPvwohQQnvBeFtrugBsgZ0MhKAjasNtxyjc-fo29fo4pqljdx6LqHDhhrtni9VB_zABCY2lELUOYemDIuk4gL4Qaiajg3Fw2dOkNix-A=w408-h544-k-no'),
  ('ChIJZa225U09LxgRwbZTkpXTRNo', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJvTmskqQ9LxgRJ4Q4KwHo59I', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJ7Vkk3Oc9LxgRVRXdBJVuxsw', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk5S8HDhcLYkQj6QA8LGw5TNPBoziaUiqJ7eP5oHQncbW5W3KBccM3JNsNT0uYAgq59h1IpAkSjx_HzOyzoQGVLUQU6QKynZ-b5Y_M2omjfra2rJn4ZRYIN9Sngr7_tY4E2ApqKhw=w408-h510-k-no'),
  ('ChIJ6WRiV8o9LxgRV0V5GQrSFyU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn3Do-dmoAtcJwV0zJ1HbnBfpeZHuxhl4Gky3ZzMW9BjhsWJw9H7IIeUSMejAn6rso628WyHVAmUkpDnbdghyaGSjZ90yr_RmysnFxUhoFq7f9sg8ZRuk-hAtxz7MpX2QpbPbFeednBl7I=w408-h725-k-no'),
  ('ChIJjzUSuoU9LxgRMSUGOOfQP-0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmXwfSwt9GDJ3PZmoz8FdWRmb0Lj67hoTEKfbnkEthao8aEAIi93imqTSqjlugUFhNsTCH3dqH05XKCrjaKX20x4AKQN1ZlSJTQBXxYWFxJXuV6qLUpM35jQshOLJiU-l-YH1xW=w408-h272-k-no'),
  ('ChIJK_iAbgA9LxgRryuxAaLoj4c', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmw04EngTx6o8oN9fQ7akSQ1f6R5Qzp6CNEECv99zWF-Du6y5JoNeZMt8M5mEaNkrekhESfvtS56h2z0Oe2BY0k6JKrAUmccKaifSSXZhcWfz5IKgY8o5-Ebfc59U-du7ZtJCEs_9bdTSk=w408-h306-k-no'),
  ('ChIJ4XBpPKw9LxgRjstxlj0OpME', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkORiZXC2Q2VDl8y5PquRZvw3dGhpu7CO0hqy8m9blKFHtEKl4gaJHVxQtYeH375nDnSMdxbCHGNVQ2I8bsB5D4_HO2JKmqE0FiMT_rs5-D8_A6s_QRMoFrQifApqIpDZQp9IU=w451-h240-k-no'),
  ('ChIJdeWd9Fs9LxgRLAmufhpNTog', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnXNI5uXZNmQLqW7AMiXQe_zUyJ-PR9oFxBNWQvwqMv7N7BNWeEKtvXtgtTorRlOoniYhJ26CTH3n3tkUBIuA9fuXWMQ6j6J52dPTTs_jCJ5j8PZvVam222V68v3TWFuxENTkNuy1pWO0E=w408-h544-k-no'),
  ('ChIJ9QDfce09LxgRp-qYMRmnEB0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmwF6LZ-bFjQMCO43MmLp-zhfwriiF-EJyl2VU9IRoTWLUbVqhSewasRzGr3kfViEU6WUWMwTMMvDS1e4rSoKZD6zvpJHDdW0slsd2u0kaOEvyzov0F5PPpX5fwosoh3kfsFItr=w408-h544-k-no'),
  ('ChIJP-gA7aoXLxgRfXPlu0vN69M', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm0ALPZB0VSanKxDsxjKrADPcz3nWqt4itnJr48UXMwX53Kgg4BL-097kqdibei2rUvvpr5yMataDjiOPU-j73C9NvcWJUPmKIat10xA5tDEyn_BWdMC3NXVcWUJoDrRu6PBDXS=w408-h306-k-no'),
  ('ChIJR4g38F09LxgRoAX4C0lcfds', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk9a-tt2jBtY8_bLAvHlIrx32r_-_MS5gmApfPbuZewlfJmPQO3bNSiT_xRffBZf_bX5UZM-7JbepYyvzpolTMqYHfAnJapVr5XMk0ZYilEZe3rkuhSVBcmZyysMUZ78TCkCJpJ=w408-h544-k-no'),
  ('ChIJj41T4kg9LxgRC3ob1vJKFxs', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmsoNSflUOqzgDbLsi8FBHNUMCiDYBaqrthD0eYDYqa7mGV8H6unYfOyMpN1gWrz5MjfcdCKzEpwkTIDscV2Zjtz-HxX9blmfEoL7LicqGNc02E5zU-w_Dq_CDQ97VcB66CQBOS3zQK6oQ=w408-h725-k-no'),
  ('ChIJQ3kv6wU9LxgR04RRTG0KzpQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk0JHYC8kKugUHOrA0vzemIMWnExDF6nVBRA73KSYmO4WJzGvxCi9VZzzS63vgPflmyVFf7406Rwo9PA9fKqw4TyiL79NTFH9_vziNl_w3cXJ7uNLWNjOv01_YMU-ZcR2QbYe-XYQ=w408-h306-k-no'),
  ('ChIJTWDsG6I9LxgRT-I4HjwjiM4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkX_azmwmhF-yW5lNBW9xcy7D9odcWh4KqB6Vgw8P6G6N9i2Yt5ubi2NlJ6r_z1-lmEtwu9Rb3aTriIegyRL862tPtfGaPQ4T4WEt85ykrMVTe4ArUlxMm1h6Q5CEM130XV92cO=w408-h454-k-no'),
  ('ChIJJeeTkpE9LxgRpU0Dnwy2kJA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk-Bw3sICJ5bfPDj12XsyOqsmN02pY8ccFcMmyKTSS9RVH8L2Debq4w9kM051V3wtNxS33dWdRlfqQKpzqmp64P7P6hGeZEQNK3_zls-7caCV4EY158lU5WjHGpPhZMqUSAsU2Kli49f5Dr=w408-h271-k-no'),
  ('ChIJiThPJ489LxgR5YQQTsqoa44', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnmdvsCYnsQTmiZt6mOLCTHjiISbDxmmQ8JjXPFuKHt-WQKoIGnyU89c8tUXqt-orFLNliqZU9JUEBBCk7EyzoIflTsdhGpm9n1CV8-VCxJwqyq8qtv-BO8kA_MmCfZxDS9hfVN0w=w408-h306-k-no'),
  ('ChIJqxCCX5s9LxgRB_SLNWIk4dk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmAR1Ph2Io9f2YeAKNyqFt4Y3mhJOYojf_4eh1tq5c576fF17Sv0O9WQ-cRRmnH9AWyQcAoR6-wSFDa9eGptZOHXEUeoKEaefnMoEroFgiCCkwsCGy6ar_vu7Dm8YMxHVPYikvuzGZZXeIV=w408-h306-k-no'),
  ('ChIJPXb_roE9LxgR_YTCP67k5Ww', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkJtvVs7u-9_MgsKBEN_P1tEz0xan-w7IZaAvTLwtEr0_EPeLEvYz7mWRZqui0Gs0vMJEA_MaedseN2FZMEbFrTn75wlpECoN-nD20gCbmqLe31JqVecZvj_YExGy8d5ceExmmi=w408-h544-k-no'),
  ('ChIJkd9jeAA9LxgRqU8m6IHdblI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlh6KY8r7XXsBWq6EKFSii20s8StVeZJ0VA1HJCeHbO3qmIkR6fcPafgdFa0Eg2sXkb8Keqr7lpiBkDUZGHaO3dxEF1u2YGChHg5o9iIDPHAPKMx1m0O7QMoBvQM2gg3Rx6ZBBI=w408-h306-k-no'),
  ('ChIJ9xevrK89LxgRC0xxcYovix4', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=xgy7S5oXEGefxhLzAsE3mA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=187.08478&pitch=0&thumbfov=100'),
  ('ChIJgaGxoEEWLxgRSPTXa2_ynbE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWntZf2GJcx86_eRQME7AD6_A-MxEg7aCNA72KwciNgSVWb7b4-GGW6F3xAsAk0qweu_w4JyML82f_GJrTL22xnl63WquRI2HSykQfZyYbRON9qrubzJhSHumWLZMG_yL07U4kJn7YsOK24P=w408-h306-k-no'),
  ('ChIJkaQvXpM9LxgRiphfeBOW2fo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnYJDXc4p0JeI2s-o7rg0WOyWvIIq0gs1VVqfZPjRPPSs48bIs_uln6Tz8lcSSysje5ZESMpCQj9tsMv9u9PpGemPat6Qt-K1WwshiGB8UJKqCPZJAAumuIRZ27lS0OUvjVXrGCUuWT-EMP=w426-h240-k-no'),
  ('ChIJBd1U9t09LxgRmhDQeEX4eBk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlE7Kd7dqD5M77dcf_2rQpAHoXAhrpUhU1MhTH7KHx8FCz_cFOkupBeClQzRqJXPfz_HQtvn__oJVmNYxxK71ywHHNckWl5pNQ2eCIg-CpyRhb7sAUtpfEMRMAbBzjPZ5csZA6R8eKk_a7X=w408-h306-k-no'),
  ('ChIJL0v5wd09LxgRMLGIVwRSuoE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn1cLOHzDWY6drB_OO_yykaT8m6neGm29_Hv_LnT8mmHUOvVXFKfkdPria1FbDBkOiGQNXEbt2uvueGHP9aKd9TS8bsAY0gvJNyyX2Jdy26KXoqh8I8ubH4u1TCwgAtTK2qVndX=w408-h306-k-no'),
  ('ChIJ8d0_pSUWLxgR3Sq4bKxdKyE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWliMBce8zeeVvuQ6-eek9zI0xvTRAyrVw8xHjNcr3vkJt_J6NQb4BiJe0HbEjjWa7hoChxxsCPVjd8-_ifAXFenJh7NdP7OrZL7uHOA0chad2fUW6AOE4NixVdn_V8Ry6GVBg=w425-h240-k-no'),
  ('ChIJXYV8mdw9LxgRyRC1FZhEf3Y', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnSzpbSlvtxWmkFPSnyj_QpeBwGR1nhNRcG1Q7gzLDcGOwBsAt_ERZHh2ymTRhUGRKdrru-EnC38Bh59BmZGm8QDaGthG_GYeFL4hDo1Pq4BnDEjAtUcJyKiabAHgPO0lmYX-ReHjqx8x57=w408-h272-k-no'),
  ('ChIJhRlKEws9LxgRtrJKMQp0svM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnjcYotBuD8hRthUzDCQ8VqEcnMtqSdEYdjU3IZ8xKX61bs1Gocvz5aXt1_eBXm2y5HNAzN433hTcpKOGY7KTIcMohbzfiSnJZD9dNXS-FO-Ls5QtyZIB6DmPLLNCypEYxrxRxR=w426-h240-k-no'),
  ('ChIJG20lz7o9LxgRm60V3mtDTh4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmocsv-Kb_REY4POY38VAfMgXTJIBJPzHELSc6g-42yvu8q1M081hAhoBYkgE-0kfsxuLfjKq-iu6YHA3flRmETbzD6k55PT2zwWqfBi63jyw8es2A4Ruaof5miH-wVzYsGR1o24g=w408-h306-k-no'),
  ('ChIJ59B4Nkc9LxgR-russvv7_eQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl92WCKxmsZxy3hlEyRCGJ_jBPATAPsjh-MkNsrOj99Arx9vt-FQnL0GrSDakPV8RAvIk7W3NgVIkFvAhwy0Sa8R-1PxWb-Cx388F_yDmQdpJEVA2ZKWXfjg_JxxD8P2GNl3C0kae1_mS46=w408-h486-k-no'),
  ('ChIJHdCX7IU9LxgR_Ndz7_x9kr8', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=vbqvtn6mwl4EhzYO3PVyEA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=58.55302&pitch=0&thumbfov=100'),
  ('ChIJ5WgUPQgRLxgRLUb_9rKuNk0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmqaLs-6JuUAj35ITYJs-SFuEK-Gn2HjmLWh3orZR8tzh6cdLnquwFWSkDrOgzrN5ptMNYZzln64mfblRiG-VmhG7ilPomly-AHu2O6dKSi_r8BUMwNVHuinJi1aNLMoj6TMmjV=w408-h399-k-no')
) AS v(place_id, image_url) ON b.google_place_id = v.place_id
WHERE NOT EXISTS (
  SELECT 1 FROM business_images bi WHERE bi.business_id = b.id AND bi.is_cover = true
);
