-- =============================================================================
-- Kiambu Road Explorer — Migration 016 (part3of4)
-- Populate business_images with the cover photo each business already had in
-- the original Google Places scrape (dataset_crawler-google-places_2026-07-27).
-- Hotlinks the Google CDN URL directly (no re-hosting) — matched by
-- google_place_id. Skips any business that already has a cover image, and
-- skips businesses with no place-id match (manually-added listings/malls).
-- Split into 4 parts purely to keep each file small; apply in order.
-- Generated by scripts/extract-cover-images.js — re-run that script and
-- reapply if the scrape is ever refreshed.
-- =============================================================================

INSERT INTO business_images (business_id, image_path, is_cover, sort_order, alt_text)
SELECT b.id, v.image_url, true, 0, b.name
FROM businesses b
JOIN (VALUES
  ('ChIJLaKxu2ODSQ0RlifKlLXSFks', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkgNp6LIPD5q1xetIODmmAkOoe4ugZgD1BBKnrLeY8LTh-jM94QmjFRVCGrYpFDWS_Zv_tR8BoUexg5gIgmxKun9YibV7SSWzb--eWBJX-2CklTCABxSo97wPO15PQNAyhCfmx-=w408-h273-k-no'),
  ('ChIJEdn-5SIXLxgRvOKuILCTbhQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn5HUZSzRLUDSG374PGgNHMOgyVr6xYhu8ShGcXFgChc1s0D9DCKzA_58LVOKB8CIx2UBKu1ySrw9jeDBztX22a4qzEBB9TYW33h6O_R1tTbAxKESv8wmwjATP9HYedKM8qlcGE=w408-h272-k-no'),
  ('ChIJrenOuYU9LxgRFFcKkLOmy9U', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJi-YaLAA9LxgR8UjpGQW3Nfs', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnsUh1MDoY2b0ykss5pea5uX8vIN3qPCvWGV8_liX-ypiL5ECMu3c7IsGZ2cn7kdE-4yBxXFYnkKnGjOi-yarPUxcw7MS2z7-8Ns4foOoMYJ_ewSMKw6K77b1JYgDMGtq1MvTLDuJRYbkoy=w408-h307-k-no'),
  ('ChIJCzokt4Q9LxgROE9FxAg3A70', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=nFqteeRWFQ4mi6auZaE1qA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=170.69026&pitch=0&thumbfov=100'),
  ('ChIJUVU3lP89LxgRhhsP0dGyi3c', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmdBLI_xArclh91RaDIQT-GHsfNkKvA8G5QoAdzv4s00xWgyn2Wgunz3UAa9rSG7eSLBIyxdgiEf4b_hAFnzg8sL9QGPYoIOmebcm33fTzYvIsd-C9ohO6J3rqDAT8emj6MmOyRt3tcbKY=w408-h510-k-no'),
  ('ChIJK0Sef1o9LxgRWFPPic9szgI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlmeeGClCAj0WznG3I1H3IbbJ0mZ3KDrhaUHPYXarU9o3yWAjScjIB688keQtVk9llBe3xpAoTd39s0VJ5WLW3zA2FLUEE6hDzsHnT5Bw27hJtOh3DLrcpA6jW51SXZlAQ69eWmOMIDF3c1=w408-h452-k-no'),
  ('ChIJ6TwZ02U9LxgR9DcIfsJexjU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkqcHGS3og_kU0thPTgKGdftLuBuDFFDVWotlUZVSPHKoPmi3ep1v1705CvY6OTj56UDCCI8kNA34MLVNpv18DsYjwNRlUD_bgeQMD1YmsUrb9spcP6tFy0Ubd6YZLk038Asig_=w408-h315-k-no'),
  ('ChIJO5STGYs9LxgR_QojiEZFdIQ', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJS-62eRE9LxgRx5CtF_KggeM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnQPoCWFfW-R9EGSvQRRCXX4JajTe8YeQ5c-L4HCDOQHPf-xrcoclJBD_GoBc3oVNdUi5HuAg9704iNi287rZZ4_yOaMWRZrvdJ3hrq61ETgMa3cYXS6m6f1udHkveAUPu8nTf75hLsszYj=w408-h272-k-no'),
  ('ChIJZVqWzmA9LxgRaNvWb0NbgjI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWncY8-eAgMK9cP0APCuKWyB1uJr79D9MvoBU6vA3COfzkjaxDkPQk5wRMjdk60MVYIHIcQWIoue9FOZiF3GjqSXNrcMxTh-8xAwcAfmJmdj9JzmHBizzVkoN7SsMTxHUr9upvylJU9yB9PK=w408-h271-k-no'),
  ('ChIJIUxUnjU9LxgRuBwJIvrqjbk', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJZ0jilAI9LxgROLhazxbfFpg', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm8-GrMcGrKCPI-FcRWMo5hKQbtgerr6Ob1I32UH6mYpwM7PMsSTWPDck9JvcielhLRvg3J5tH9ZcFr1gkJvlRTFaaWioncRqcVJF9mtB-zz7HGJAvK1rX9W6K7W9RfdVYqoGEtW82Dygh6=w426-h240-k-no'),
  ('ChIJaV9MlLw9LxgRFkL9DgcrBgw', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmHjopQiiupRJws8DBe8Epph7Vc4pcxuz4BrKnK4RqBONNetDzsBzpL-vr0DIu9opZaQ1rqNhv4_1OwFpvSYVVO8fJHdm1tMSKbNrrDOfxxNlKYhb7hfr3WWMA_iGAx8ky8HOSSUD4W1js=w408-h544-k-no'),
  ('ChIJEa22jRg9LxgRT_4tao9SD_A', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJtTCKT6I9LxgRC9Ku3I6PN04', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmMyFcSW0pzhyYx6Gz5-ObgI3L9-k2LrQfVWnsbsK1scWJu8Wv2AUNTnC0tA5hGRgL4uR-Xq22S7BIG3P-3K0zpiz-TlDI7jIpStAVjP9F2IXp2HLnpNU-mWvwdOsetTQimpeDt=w493-h240-k-no'),
  ('ChIJU96MDUk2SCMR_IoPV4_SaT0', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=MI-Di0AOIQ7Nw1UAqSjuHA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=198.30797&pitch=0&thumbfov=100'),
  ('ChIJLeAm2oQ9LxgRSofavkE5zDY', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=YzsdoPK5TnNzdv-cnj_nwQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=269.25513&pitch=0&thumbfov=100'),
  ('ChIJ6bvYDB49LxgRpYJCYbT0bnk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnpvHYo-UD5dJtaojLpca93S23NCifcsYEt3S7GA7Xaox18toKUpzx-M54iWGzkaL3PgKyQMcLWJI2Wh3FdiSgpquwYcZrej4CAvPfs-HGCxtKQF85s_GFdhv4x_EXCxIKHXDTA4w=w408-h510-k-no'),
  ('ChIJYcDFFrA9LxgRkAa3pmeaDaQ', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJ915obW8lLxgRBbexK6yWAsE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnJxy4HPgFPIlaQSzVVeXnm4f_-QPQUMALuy_wjLRhEVA5OCwJ7TYWPtsVPwBl17DGxztY0RyJ9IoGOmuvnrMWv9KwH7kJzY9TgDBWnZTCK2-K5jKfWy5fY-yrOtCIWC75WBHAP=w408-h544-k-no'),
  ('ChIJX4jONQA9LxgRfstfehDKPJA', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=rZNU9wfAj8z-_0D8fZMhAQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=274.41074&pitch=0&thumbfov=100'),
  ('ChIJtQyyBAA_LxgRrBt3jtCsKPA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkAm5kuE4J08YYqv6Hu60x5pFE2hHwIIp7rtgaKvgSqTwzgMTVJhO5xO0xeryHjV6e4IX9TbdMRBpVtraakVt3kxkniNmXJvDcReXQFq5euvXF1WMbmeUmeANV4tvS-eXQFBJGJT8j6KXf0=w408-h272-k-no'),
  ('ChIJ9eAtAwA9LxgRpYvehMZ51ss', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlsAeynjn-K6YFfu5IZ1F4KDuonCIbx6fI_463Bkr7q9UX26uJGCY-9wJtTkDXvPRbu4hcYcj9P58LV-zIxxswRGolk3eSypXvOopeCww3cW71fImu8277A52jbP79Re18pYnyYkmxqE26-=w408-h544-k-no'),
  ('ChIJKSqhi6s9LxgRQH_ZLE5dkrs', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkGj2dfHOBeYDFwPnvw2NZ2f8Z_3hz2pcdrAApmeb23j2-YxpZTKxwsM3HyCwIXDOPYS64qL0HMgikw3nnk4LMhueGD6_1NyTatsk0MNJgJq0ngV6e-vF-w4RjNUlk3Gpjhz_i8AgMuXixX=w408-h272-k-no'),
  ('ChIJQdrEq089LxgR6W9nFFN8TmQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmajjTFt9L7uSrR5by3ZkTB28z4Ayg99st_wg0H7_pdbiW5jacL7UYGvOZFbyzgZSBKaWwMRa5QYZY7ryepujX34C1Loj7uS9pjZNr-aqT7C60olkyXfr33D-8es98zsowhVL1H9FJC_2U=w548-h240-k-no'),
  ('ChIJB6Zgimc9LxgREL8Qs1O0wOc', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=o-WBLWaWb40w3pqFNP11Pg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=271.41327&pitch=0&thumbfov=100'),
  ('ChIJhT1-CQAXLxgR4rexlwUkQ88', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmYCIs4xae0Vbdqvi0aTP0HFm4SocMVoAd5o1Rt7sPI0x6dnCkCVT1_gVrfizw-xxzsOGd-3Y97_Wd5CdHFop_FeN8M9uSTFx4FcB6AyqucoVbrvjbEN3vylkzgtxuoCSTd4FqUhBuoxpsx=w408-h352-k-no'),
  ('ChIJVyR5l_g9LxgR6mY-PUFPlIc', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=e5Q3OIBenOJGeGRZgcBSig&cb_client=search.gws-prod.gps&w=408&h=240&yaw=155.87535&pitch=0&thumbfov=100'),
  ('ChIJPTu9Cxg9LxgRiA1GoMXy6MI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm9Kzd8Bqi9RSR31YIciy_FQDJrNrnWruady4o9jlxDPCslGoxewYPSPxZRjnL9YVzbcz8LnMG0-WfcpmqGk_BLgEUk9a0CitCSOHzNsnBu-jZy8ev7JnX7xYAEwDRYrz2L7Qk=w408-h268-k-no'),
  ('ChIJI77PGQA9LxgRprKAhEaMVSQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWktiFtkx10BKHi9Uq-BxcclTNud-N7nAE-N7NAQolzYjqYwcNYw7frHgzR55bZSArF1iw5UXdORQ7qS9cABANWkLt8aLOP8QZAo5ig7Wl2SiAcihYAuxrfuf6GBz95RVjU7Q6nJS3VEbcJO=w426-h240-k-no'),
  ('ChIJbQZxYwAXLxgRFMM2JU4bZoE', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=oBaxp94Ji9v67veDrrNF_w&cb_client=search.gws-prod.gps&w=408&h=240&yaw=23.216988&pitch=0&thumbfov=100'),
  ('ChIJSeR9PLAXLxgRTZS7P0uPjWc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkTMkyckSkXiOz0nTV4C-i5ga4MXzsDslvqRFhuUEQdI6qqcITq-8G54NvV-J2mFNZjnC78-2Yz4rA4Zl59noeRqb9g1k-Rqq5nNLEa_Y3r2BTFPy_qF0Lg4tobih4HePpmzj8hJc5kNNA=w408-h408-k-no'),
  ('ChIJPV5gTwAXLxgRuK_nmZhHkKs', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkarefVDpChTB1NU3fwsHUs5xb5H0VQSZL8pmFjVUL1FRe3akT8JfCa6NU1vZrFY_hsvwjdf9qvihj97l-rW4ucvsuZUKO-fyWN19fE0IHBGI_4FKfdFUdJ5SenQI3VlgPsmaLGrA3MUUA=w519-h240-k-no'),
  ('ChIJQVJXS4Q9LxgRNlJOUT0zd-c', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkaK2tCdGTPYrU6oBT0LrDG7PbAzCfWRSu2fyok5bcvrXUrJzlSCOMTtVDw90mdlp1Ez2LHnHlG34ljWgXWryc2ZlGY04UGJLwp8FlwjoVN_8_zB4GnPsBhgijuTVjyjIpxaWbn=w425-h240-k-no'),
  ('ChIJT2vEojcRLxgRrBJJ0IERDhU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnRe0_Lz_Z1aJ9SNgxxJEm-JS3pUUAsOGZKXesOKPsdQ2h-CnFkoU7xRFP1b_DKvXwx07iuyh0H6GT0HWvSPm_BWv85qgCQMFHiD-WSSZsz2PqmyNsQySdgfiREGnD5p7p5SimL=w408-h544-k-no'),
  ('ChIJeWTlVAAXLxgR7DJOGYmcpqQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlbM2SH4ffkuVmjR3AFekYpCfEHtG59JSXcs2b5BEAAnY0nxmohf_vIY0iJZYQhcjLcted6lzNn-4T-Oqz6QlQ2a8kNgDyptj7iySr1O_Gu-okjXkvc5jUQdWcFaQtcUTz0VF2G=w408-h408-k-no'),
  ('ChIJ4XiyhP89LxgR69uzD3LsYKs', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnM-B7z7QvB-qpKGAsNUoTYc92amUD11piuWxP25wnHtBUEFj_5_LdI31zmc_kx3kGjLzSO-P1NM6qFOqf5eE88nwhJW41UDYHDguw1iy3g4jy1x0hnCVkY6DWV4rKuPPOWNZicHQ=w408-h306-k-no'),
  ('ChIJQ25BfwAXLxgRQ0b2ZrcUHxQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk6KpREDEZn1YSsFdKEtZm1-fcOK68Zm3zakSu9U_dqsVs7AFcaT9jZXrn8GObHbfyTD2Loxtmy1McMw-hH-pmX5kYhqjikKi_CFwnO355YXgT7zrKxBDHbr07hKDRKTKvlQrQ=w408-h408-k-no'),
  ('ChIJHcbu7IU9LxgRyIJSm_MsSZk', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=mltrQkZ9TiqqgLtdWt6VoQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=195.92996&pitch=0&thumbfov=100'),
  ('ChIJ6Sij1IQ9LxgRNXcdNsv6FZc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk_Kvp62YWHCtDwAZSMWSpWMnOYSgNVbzzcGFCvRArAtV485S5bDwPOLkWSpPHlnNJ93lAnOtrcoHT7STDr1tp9nrwHPI-I8TwPqFqe9oHnDkFOzG8kB97V-hCQWmvGimx8fr6W1Q=w408-h306-k-no'),
  ('ChIJ7T04dQAXLxgRJ4I64Xc3Rfo', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=o-WBLWaWb40w3pqFNP11Pg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=278.39633&pitch=0&thumbfov=100'),
  ('ChIJC1lwKy4XLxgRJS2qSgbHvSA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnHAwRFZtL4XRPDATYWtLSRU9Pou_lfKPXe9y4G0uRPfJ-9Zk3xRTvEZjjgF2CqyPzbVuWSJ4V2ak9SfqUWKz88uJ7EOQ6zxCqFPMJ3pJhLshvXrsk9mSZEB7dQ1CCWjmTx2JAY=w408-h306-k-no'),
  ('ChIJgeKAS8Q9LxgRO7FUpuz81kU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWllyKnvLl8RI7QTMDA1ywyS-rdcyf45N4YUUfITDKOwxtoiaC2TIC0cpYOpEOGmrc99TuGx8mE4CRzDV3wVt4vCHLaicr4hxLh07dmqW5_3BXEKq-NagWVgjn4pBA54IEms1Lzo=w408-h306-k-no'),
  ('ChIJ_0lH2uY9LxgRbPA9ucS9ntc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWndWps-JtZqNiydWD-qpx6sZdk77Txj2JkWC15INirtgoPRDVfhPb8geyFksvJlUr_EzLyxpr4ecFPGzt8tCmtUdZYZw54ucDNi1ktIlHw73TJy14RY5qi8TSg1TcoKriT0gL2uPSZM9ALv=w408-h544-k-no'),
  ('ChIJP0CRydg9LxgRaPfBOi9L0Ew', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk28ExE7ncgZjCfFjDS_6ivwom6INkdP_ORhLoIGZ5LB5r4tcY_niLComIWBfI7nrpZaNz_HSpK_hTz-73EFSNr4VIyEVNPSVwyVMXMrDwU5sKSiQ7lC36S9PwjIN1VrqL5rRPJ5w=w408-h306-k-no'),
  ('ChIJwSXJrYg9LxgRDY_D_KnEuho', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmjP_BVkpBumI47c7gIAmcy5pEU-WmkrQLynJGyzB64P1aWWFXfYsScEBamjkXO83xTjK7oP7yQra8jPT0zQrAt9GMar5wBx-Ax_37FWUcdfdMD9XDN42QdIK180r1XUkDpbKY=w426-h240-k-no'),
  ('ChIJqX3-GUwlLxgRnHJVomfoe-I', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnLjcKVZGINgOBX39X495SaXTG0k9Kgp_YKcmxZBVozF2p_LiU0CaEaBFBajdLrJhLE3A7FhmeR5uMcxVKbN24hy5YhVTYZmy7VsNIa2qnEgZXB-HEii_IY63bbHyjOW4GfFNjrh8oAVls=w408-h307-k-no'),
  ('ChIJ94Se2hE9LxgRdQaO-YaJByk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlQNa6lzVUqOw6DQkH9lHwF_NKww0516-sizT3vQ6oLJJmyp0ZPKd2vxFU0trBpvwSPOlKCoEtPURvob8Y4yhkxUjmcdFwQgt-LNtn1Yt7U42kEQjO-wb0SOAEhvZcF5SNqNgneqA=w426-h240-k-no'),
  ('ChIJhW43fGoRLxgRxuM01EVhWts', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmXMlf6GAkT8gwf8-IRvhcxO3trz_tgwClNwfUm3KfIa5sDWTmg0EDAGJBk2AUq0JGy4qhvKmMZMTshgQQfbKqXoWCBXfnfqCzGaGyfyr0-MVYNZV3vgNBa6u4QDS-wtOl9gPNvFma3wQI=w408-h906-k-no'),
  ('ChIJYw4--hs9LxgRUrUKmFd6-d8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlZQXLjLJJMq132dqrvccKczlu20IXcleA1S7rXdjLNQGcu_EJMZmuzxtqI4fFVmceBP-NmSRa6koZttZH0uV1VUk5uJDQ2YQVKU3xSsspl58UVwmDhe89j1JJBA-GeFc1aoefu=w408-h284-k-no'),
  ('ChIJ1_W5EQY9LxgRElYgRJqxIzI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmdF_fItdM_X3nSM2HoHmz2vbOhBLLyQt7KRG5x2P1XvBohfydXEHqIPGDk1bokEXqVdB3L03JT-AcixHFJapgBaa5yfrUt-YDL7LvhFWAoliTQNGVp_MLp0RzUi-UOIbiuy20=w408-h289-k-no'),
  ('ChIJff2ZeI89LxgRQNLIBPdXB98', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkPWm3o9sqHsKNuSMmuEvPyxJodsvSVcbYA_GMw7Xbk6zGcxAaJXHvTnGz-KUH3YcWX4wx-55817mkL9UcnJnjf7GNHg_I12GO9KOhwkDVIvVAMuHxyyL4yUn2XLG8r3n0gq3Gx=w408-h306-k-no'),
  ('ChIJ9cY394UbLxgRQAVML25e0PI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk7_c5EjcTYzxX3j8fxyTw51ywvPJfO1jQ3Tk8sLZj9T6lj-G8SpWMFMZMfAJPEXkE_OI9fJeXJX7qlYhjzW8rksdOQbrSZ9euHJjo1yTEAjt96VYfphh6wxi754SpoqVeYbIBF=w450-h240-k-no'),
  ('ChIJ5T-CK-QbLxgRqvEUxoDMKfo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmMhQJVczjUmXwcZYG2O-3ztrKlTQpJsDIASA4xUaFGr0lOzUUpf9MIMHR3JGWjb15gAINcXtljlFwRdPngiFCONOG6Ex8BpdOQDiFel0X7bUSSSZbNwXp5fKqxJ74U55aZ6lb0ICSNPYQ=w426-h240-k-no'),
  ('ChIJQdMlyQM9LxgRUqeDFOZiD7M', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnqXBgS4UJM7ubOOelbWmDl5VJcuZ_BpfExPBUoh54WpxRHrCn3BhQzRCcK0QfUgM8_eCW33eUcce_0R-bN0nSWw0Vr-mQp4nKmRf6nzJeOMTbDWb7xrttil3c-wJvFpBHPCWqA=w480-h240-k-no'),
  ('ChIJz-jSXYY9LxgRV9MXsJsQMbU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnp8uPTi3vfgXvr2225Q4dScA2AakJCX6oB9wauCLYJmwkAAnLJ-Qek13ErBnSGfmMzzvAZnyAZROLIM4aAE4lV89n4hN3035o8qa5ZWL0KjfY1ZRhMO8dE-4AMlm4g5_FWfUA5=w426-h240-k-no'),
  ('ChIJY7Htvtk9LxgRejKFm4mSOuI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlykxhHpvGuy__miR930WSiwbx1ID2dKzADqH_4gj_o4IjZ5829YSV7RmbgRZ-4nVIQDJIpXMk8iEBO7vV4gzW8-goeSIrH-S-x6TBgpcbsxj0vtwrGZiDz6LfZiL8UMKKGSxO6Sf99n62p=w426-h240-k-no'),
  ('ChIJ2QCHlPg9LxgR0jaQ1HxI40g', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl0liu1IJhHOFUqefiseUBwhG4FRi0QFfo9RTiCyXw8fwulwplmAXWnVhWNQDRGPAr-W-M2_TnmsrBVxQPeWaI91-FWR23iBterje8jAJjPSk9hIPgTFW5a5iJ_q2yzlujydH0dSsZr83cC=w408-h408-k-no'),
  ('ChIJ1UyV_N0VLxgRkcsLhLeP08Y', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlbYHpoPlNwvaZ_buckUAKk3MKBxDtnG6hhMPyPNjHmLxS-CPWzb8vkvuKay7HJdKt4oDmrc7qqTGQGJrYCBwSiKxjADvQNuifoIXq74KQg0FBwF2z5YsfaQiApRD3Ks4I9OkeX=w408-h306-k-no'),
  ('ChIJk40YLBg9LxgRBzydsjX_pP8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk8MJgEwcO3DZLXGsKPSUiOhDdssdlOgUbn--HYBv5dReZiU3ZeYQITPrN4HWKczfb_vKCMOgwFyr7ypqBXtwF0XdhNJvy4drEwMQs8dYibb8L-XnQAHdkcqV73fFubxfvJ-yc=w408-h544-k-no'),
  ('ChIJcYZOY389LxgRFbBQucS7wAc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlw5gO-rppulVZHAfBOKGP4_McjaXFDyVxQEjqH9i6DwLCVEltbLKhV8ieJCLkMvR_gxCMqD4beI4uBrAcvAU-XqmKZuf5pYn43Q1v_pQKCnWdOzKTI-c4zyq7I7FhuIE9_aedd270cN77p=w408-h272-k-no'),
  ('ChIJV9jT4CU9LxgRt5voML4SLVY', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWla83TQaSPGQq_mt8b73kS4R4c7DxibCQlLvvF_5D58VSnnVcB04X9eTcemHoo6QXdRZZ3QBGEHlC-VFRZA8f42hn737JR9nQAZVbdD_RXN2YBbUePXQNmuoTKH1BGeXw-3cOC9rZqPu3c=w408-h544-k-no'),
  ('ChIJa6DpjI4lLxgRbL8frp4icUY', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=SNMQpuVrxoqpIN-gqA-ZbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=3.5408945&pitch=0&thumbfov=100'),
  ('ChIJvX8UPQA9LxgRLd5wUeSgxfo', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJp6uTul89LxgRac0kMs_lFfo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnadzCxDHl9_CJb0VJ_MsF9b-s1c0drs_WQBCtICKwnDIz7rQwyyqq67vZtTJKXslsUzOzgkUii_gl_2DanKh_Dxw5_hGqo4baCHxrDHqFx6X1kXzKMVTUld7YUuuU3CkA7xqYJqg=w408-h487-k-no'),
  ('ChIJb8MlGhw9LxgRhtXF1pxvx2s', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=QOqndHy6ArFll52DWNtLbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=156.28949&pitch=0&thumbfov=100'),
  ('ChIJEwB7_4Q9LxgRkahWXMa9EPQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn-n_l6JNmqWatqhozQ1cQOo0rq-U7FN167sw2AJdH6UDBIc-GmI534qiNA3-zmRSvXQgsKNmbLX7FX2ljv6RzcG3vg-VBJWKrK0YNfkqwiv_cWbhwRZG-1fcydFEecsehVRbLuTJnG-nMR=w408-h306-k-no'),
  ('ChIJEysWsnE9LxgRUSQtWslTnhE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkrl_ak5n82BkTftVK-jyFWogturYmztqy7muZykUPROxATcr77G25fHFycscM0Xoj9CIemYYPCOWGPgLZZi8aNUKPO-SRvAQ2LNTk4GAzb8_bNJlnWqor7_Kq_j5_AWZg3lkwe4w=w408-h272-k-no'),
  ('ChIJFRCc-C49LxgRcCslAZwBdHw', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=p7NYHpPbvA8kkHalHZsP0Q&cb_client=search.gws-prod.gps&w=408&h=240&yaw=238.18108&pitch=0&thumbfov=100')
) AS v(place_id, image_url) ON b.google_place_id = v.place_id
WHERE NOT EXISTS (
  SELECT 1 FROM business_images bi WHERE bi.business_id = b.id AND bi.is_cover = true
);
