-- =============================================================================
-- Kiambu Road Explorer — Migration 016 (part1of4)
-- Populate business_images with the cover photo each business already had in
-- the original Google Places scrape (dataset_crawler-google-places_2026-07-27).
-- Hotlinks the Google CDN URL directly (no re-hosting) — matched by
-- google_place_id. Skips any business that already has a cover image, and
-- skips businesses with no place-id match (manually-added listings/malls).
-- Split into 4 parts purely to keep each file small; apply in order.
-- Generated by scripts/extract-cover-images.js — re-run that script and
-- reapply if the scrape is ever refreshed.
-- =============================================================================

INSERT INTO business_images (business_id, image_path, is_cover, sort_order, alt_text)
SELECT b.id, v.image_url, true, 0, b.name
FROM businesses b
JOIN (VALUES
  ('ChIJoUFavBc8R64RmUPi-R3eLKQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk0AKHieYCW4WGbQaRIHfpLw2OWoEM9rHGfBpCVQWGvKNvO5maL2aKNr0sYvEItG5nqgfkGnJjvtBSicuqBX-98WXqv74HkNqh5VMHtBnzqc_PU73l8Y62TSSn_9wzzKm7d_bLkQsp8u2JJ=w408-h272-k-no'),
  ('ChIJf4pG35sXLxgRsrBdzmtJtD0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlaQ4ANsizR-BfimmQN6KaKtA-s1HU4SPhvSBh3dJP5z2bdof7FBJXYl366sX8rmyzao66BCApsM5PZ1RX-rx2OP8t_bQHwiddKrcfy_A2Yu8AbvvTicvePg01y02ChT8ksxz0H0GAFFOkq=w408-h306-k-no'),
  ('ChIJaZqla6w9LxgRU8YcEGSR3Nk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkQvR-pwh43LiQz6iEc8wW_13h4HR9g2598Ao8KeqOeI31qJo6n8KK6foH142i3bZxb4yThc8EGNKar66F1UZaTwdxLP0Ypw-bDtd2GTFm-2rpm0jLUoOnjlHPej4nXeCfHoQc7owsbTIQE=w533-h240-k-no'),
  ('ChIJOS2rAYY9LxgRtzsEs9qtoho', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlkINjMs5c5uh4J8BgbHJRM4PT1gUeMVZ6hi18Nh6Z7Og-vrhfuW4a2BkZCY2OyFgeMDXTiTxobMOjlJBmtECCbF9OhbvTU46oOauZjCBNdVwV5rEmFKh58jDGpirJisQePLDCkizOgmqF8=w426-h240-k-no'),
  ('ChIJmSsGgsM9LxgR-BGOH2s5BDg', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkgpspfmi-jqXRCFDoMNMsviycp-436jJRIJc3O_7Dzb7n2rk6XFGvQXPziCEYJ4FSl4j0NMwA-T4x4kdU5FaXzIQnA1sTUC-Da_zICIX53etHPGzf2154jHpgQkHIr4-Fe4y4m=w455-h240-k-no'),
  ('ChIJa0MY5e4VLxgRD3UaPWBSJJc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkzvtG7myXduBVcjjAMZJqIHWFjliArg2hXN1pGWAHUM1j56Y2eCsjXhBGLZYND662DE2KpqI9wGMg2MVMZNXGJvOC0ArRe-isGyL7WfzAYxHKEG9ZovCKZ3NZtuaW2OKAPd2ec=w408-h883-k-no'),
  ('ChIJY0ubWA8XLxgRKqh6g3NvH3M', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=1J2T3k03eMyNixVgcGs23Q&cb_client=search.gws-prod.gps&w=408&h=240&yaw=274.5847&pitch=0&thumbfov=100'),
  ('ChIJJTboH6Q9LxgRhjWZpL3hB70', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=RWcrUTBHVPsucNbP94im6g&cb_client=search.gws-prod.gps&w=408&h=240&yaw=270.00116&pitch=0&thumbfov=100'),
  ('ChIJ4cTGUXE9LxgR-YVy0Sr0f_E', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=p7NYHpPbvA8kkHalHZsP0Q&cb_client=search.gws-prod.gps&w=408&h=240&yaw=241.97812&pitch=0&thumbfov=100'),
  ('ChIJ3XeLwyk9LxgROEJQ0DoLdWo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl4rvFAeuMOdwqSfGeD3-k2X55HKT3qozCX5BGNoOEfVG0DWj17G84FiCMjzbjy85rm1-RFpaG_qFBVTujMsqaXmX0KtxAgma-TwxNfLn8HuatBSrVXsPn1JfppBwoMCkej0JKV=w408-h408-k-no'),
  ('ChIJ7378ZK4XLxgRFmwwjBn7TEQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlJRQpdDljjgbNbiZX9-fZeeKM2818p1F_FYZSy1pmRdE2N1RxsxKWtJg9rrS8kjjf8qER9D7radiu30AANaFLm-6-CYaoU6GnNOgTFKgbIYXIpQubEc7j7paGFUSB8twJa-DYg=w408-h306-k-no'),
  ('ChIJ80GDEQAXLxgRGKWVomossX8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkYiliBtCTX7BB8ThfY68-lVyJZCqXjfcG9J6bKOgys5MDzMXeMiC4x_FeBj0_PK2KP8DXe70CfpAOosu_xLPtQtc73C2n-QBM-K5rRQP1lIDG4JUWG2FbyAxilInno2Y-2icaW4Kwb3MOc=w408-h306-k-no'),
  ('ChIJHdgLecc9LxgR3snt7XpfJT4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk3DKcYZxA74omYtIPyXamHlO_-dTh2xHZT3zv37bt7MP4HkmMjJJ7xVoNpVfxucRIO_D8_jbj8LU5NWHDvIm26yMcrL3DxLqU0Kg0qyJiUxiu06qW8_vny4TnoWQVp5O5SDm7F_AyA6IE=w408-h306-k-no'),
  ('ChIJtQoxVsw9LxgRsgh7dFV0TEw', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlSpzuuW-xi-QuWgdfbnRUcFfA5k5B15rHURugbSAzGj_4tspXF3r6TqY7hN_OZWjyr_aPpAeB1aKxHyA7axg5Y_ePp0qefJLej69iwjUnBc7WLBJd-WxS9iw9H846LKiyXZQWHJjc2Xb1J=w408-h884-k-no'),
  ('ChIJMwYlomwXLxgReK6_tB_dlBg', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWksdq_ir4JYGoqbkgS_VNJqBi-rSmrMBX9adE7f0nd3utklO3Mu4_kICFjOH4h7v_XM2D8YIe-E_3bzcb4lSBGsOvGFwZZEFwhirz76lQpjzHdETwPoWN8zJC544P7EONmo4SzkZaSyn57I=w408-h904-k-no'),
  ('ChIJc4dbBwA9LxgRmhhx1u2ezQ8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnGi0WSE4H1Rh9XZSfrBJBXWQ7CXWMEonCZaZ3qBANnI1VhVWpZUbCPPLeX17kOuVUcu0y5cb3aXZ3XbQHpinkwO58c4WzvoKJ-mjyvC2uLjQ3WTOfHF1aRX_f-ju6sKTIRtu6HiKWkMV78=w408-h612-k-no'),
  ('ChIJhegELwA9LxgRWjCYcfitDb8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlM1WgE2VxF11r7eyG5IPH6Y8lIjWrR1wQLwLTu03voAXIDNKJUK_EKSdXM8m_RuwzAZ0IeaPf74DhUmpjHRzu98qzEogupjvyXMMHtgSd6J_TO9Qp7qYfcwgwPxyMiYkohJoY8Yg=w408-h306-k-no'),
  ('ChIJvWULbok9LxgRFm-vNCo5_6U', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlR22OS_42Pfcdcmslgt9jVhfrJz3vkRUwyqPOEUqq_7f5X_eIBdFQgfcv57fWWqlPGA54GkxW_KlO14RJg0UZ2zkn7qaYoH4Udjk4lwUGtWmyMvwURXMeps1TkkM3hjfjvI6TuEWdx3WKN=w429-h240-k-no'),
  ('ChIJmXmeDz4lLxgRfxtM69Jkzn8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmhn0FjChBq8QMsI65GRN5gr6nQPpcFMW1RekAyd4ScKIUpokVsWQtk9CCD8HgTWeYhhR9VLM-i2c16VJilf2hZULFjSzO_EXC9mM1QnyTyX6c4dkGnVKJQxCj_U9AbUym0Gc15AA=w408-h272-k-no'),
  ('ChIJo4WfUmY9LxgRDHD2lnO-wLE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkh6JP4uMzdlIf5k5XL2i5k9paxRt7dAJpn5qAHxJnWImNWE0kSAcJr3DumE3H-T7TCJdmirf98bmT6NcLi58PHrVPpHHaLw69VLnWsZAWfh4F-p5TNq2j4jy-l99k5GuFEcD8=w408-h929-k-no'),
  ('ChIJ4yZHUyA9LxgRJVKTZB0poLc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnNEaVX_vtYQ-JSUnBbyB16ejO6X2By0b5CyaS8QkT5S3dYMik7Usyw9qTZS4xnVmVcqvcnCtUXc2fzIpIIc6AAQdB5RbpeF5OXOsvmiDKJsS53QriLm3eLnnU08uX3E_o7LwI=w408-h544-k-no'),
  ('ChIJ4RnovCUWLxgR4fc2uGuQPrE', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWncYBHEY9mxk4srNp-T_D_Tex6wvolCisQBO6ZT-iNEDMWMu0shjaMWa0_VlUKpisyZG-WG10lUw9igq3kwcjGwuycNU8ihVvBZDyK9H6ISBmpGed6MiYIlS9tnjQqZR2DldCGyouy_XLRj=w426-h240-k-no'),
  ('ChIJOyEYPQAXLxgRKnatSUv6BMY', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk7fFPVCusok96Usr4wAd5qDoVdYyfGqk-qiHRLnVIgZhmCypm7b116zroezIk650hz5unMUDT7AymKVrVG-hEeZ69FOExpkKhkWjAR94g8DFVFAw_oP-aa4-7a5RLD9qjxKHaO9P937AW5=w408-h306-k-no'),
  ('ChIJfQ6p0rUXLxgR9s766gnAXXM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn5AUl0OeDn2pdItd4EeqeMo6mLceuGS_HMMlcY7-oO_mQDyCNokMoewW714TTdQ_c9yvVSoRSSNmkiZHpVrI8Pz9V4xyeKVfsaKTzDTeZ1X3B7dgYU6DwDS8YvprFwY5J5Pe8how=w408-h306-k-no'),
  ('ChIJuzTibgA9LxgRtcB3JFHUWjI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm4DYfP8o2d8iJnKTAtoNtJ9SCUDLWeIv2Wr7L38i91Y6q6brsZ47W7K-cKvns7LDatQabVIbx5VYDc0h3AX0vudHd3a3zwGNIifno7kLPuonkP_GOXD8YQBMp_nUJcMPv3okFb=w408-h544-k-no'),
  ('ChIJja0_K4MXLxgRd2xI6Xye5Fc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm0zlHrFbMtk_oMvGVq9a7b-NwQl0S69pUSQoIj5FxaPS1mNIqLLet144uW9BIOkw5AwfvZ7uZeKVPiEmL5kbtGUzx6hhh_NA9XUSZdtGZz47pHjCjjvYZrwW5fWvSdYIBudsV3UEuLSMKM=w408-h544-k-no'),
  ('ChIJxevYfR09LxgRtUpT2IbqwzU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmlvl8ZCtH2lDQ7z3krEgfcPzoDy8IIXUHa6Ut6bkpKY6gt-bdbt8xbdCUmFOdr7SZmw_Uw4qkUUbu4NzNMzJCIqAc6ie41sL8VwEZXx2P1enMMNv34CwEjz6U9OsmJtd_wPn_D=w408-h905-k-no'),
  ('ChIJGdstQ5c9LxgRvIjzcTKvduI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnzLBLBjfwwZKE6knH4dt5-Kn8PyleIjGWSCP6FKLpI5hOpBWEA7gMw8KmCjTOKWmRkDmL8mF-Rdkl9qxs_GBj5qn_TO5nEFmJ9659v_zYVPg4jkKQ1KnOpDmy8EtD9NGIez4M6gxNs4qIh=w408-h544-k-no'),
  ('ChIJSfR6EgA9LxgRl4HVsmW7o8E', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnh0z9yD4nJCTxNyBT75TGfD44kBNUA0McTe3g5Z5PoUCLSz8-haG6FPuGrAPCz6i5ouqJtqbuF3QfZJVtCRvOVHSDJ-arxjl6NVaZgpmP7FPMDI2CjiekCo0FI8k88_n2Tdj-RuzEbYmab=w408-h544-k-no'),
  ('ChIJX5s-pOoXLxgRHy3V3sBYVfo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkOgtzcpxUrwn6ePH7vPibvGxLPAruMd6FlqtQPxdNSLZA5UKGG89J3dTek7TJ6ouhMyTr7disaHtKReuBOsEk1QAEEhXaOTUdz4x_Tos9jCzQsukxF-glMcaY1SZIGGYbgG9JkrX6UV4Ll=w408-h725-k-no'),
  ('ChIJBUOAfTgXLxgRe-5yAMMr8n4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnNi8ZR-5UmM3hvy3jVFr8DtP7xq9g1_0-22GjWp6zVgrtyTD8gkPtvbSMhSvfrE5PBM33jZ8rLDbKDTWQjPLYBwNf-Va9Vku8glikPXlxyCSQxv2ElGt1T45l08PdcFlRpLUGJ=w408-h271-k-no'),
  ('ChIJNW_HHAA9LxgRe7UBOlcrRuk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmvXZ93e4as3ShUKn91UuMRA3X7kAbLOQCO2Ydu7RO6BErv2TtduHaeuk2cITyHWxlDQ1cPybCtMHiccHPjgj9BXGbqOu_5EFSP9NwdRpcIkKVVwQD20vULZ3eAePJ6aHqM7Ns=w408-h306-k-no'),
  ('ChIJcbqs7co9LxgRzfpaS-a19gA', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=GRSBaGBSI6wKzZQeDhgdsw&cb_client=search.gws-prod.gps&w=408&h=240&yaw=177.35861&pitch=0&thumbfov=100'),
  ('ChIJl5ltoCUWLxgRCFkc7amGWKI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnsOZu2ZskqMvbQViXSJMOfGQDs6sIQAf7jc8WXPjU2v0ZF2zcYmhJS1062htKcMCMOHOT89LmKKAwHXTCmLHHb70DoHFn-OvQJFc2jD8iUX9wsPwuNFfcs9Rm70JfZ_5RqwZv-oQ=w408-h306-k-no'),
  ('ChIJi3pBg2wRLxgRSgmtYZCcmyg', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkYg6i9SNcppX8ZH3c2EVx68__0R1tbSEEAM33BGHVw3Cv9Vk31WwnHAqh_KRI00lBpICKXQuYYZoOQsAxSS94EDTHGQCKE1iTxvEDqyb7jvnkBo5rN75EMk4UabxUUrDtc9ydQBnTxVerV=w408-h544-k-no'),
  ('ChIJdylNpSUWLxgRE-i-f84M2i0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkcF63uukmint8qLDIkaH0CSQ5nPrntsMeq8kFazp-ElRw3z4WfeO8pJ-bmVXRMe4wetO-0eFpi5VCke9RUrYHuFVJNWRA_7qqMc9Uxiwl6EtyipqATB9FDdTBTKMdcdfmyjuaa=w439-h240-k-no'),
  ('ChIJlzqbZOMWLxgRi-IbnoPZazM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnq6s3Wgm1qoQ7Gzw_sX2MERkS_CHvSOk-6okmH7RMIYZHDgvIawQhDV0WWnD8UsvqZwvcqU1FUp8cHUsYoosc-CE9RqU77_MndBxsZ6F2MVxwaHFvLOGJze1zMzIcz38OkoRBnAG9yDYI=w408-h306-k-no'),
  ('ChIJp62TVgA9LxgRXaNzoPlnVMo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlJu4OF5a0maA1Hf3kY9pnARk-h9RhRnN7r8w3p12nO4FjVnML6Gn9OjLYfqX9SkoNvQUZTHM2EO5XAfvmUoHqieAj0muErthOwHYrZpRNI2jouPuGcwT3qI5qLbIkDGy9V-DH4Dg=w408-h306-k-no'),
  ('ChIJQzvEVs8XLxgRMEr8NYyh6I0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmyVi-Fn7sjC32f2M8MPNkxLsITE24SvBf4dNM2KZHfr5Ar0FdNAWcXUF57hwb2fKCOaSw1Q2E3ki8qXZ3FYd6AmtOP-iTEPzJZeSgH1Q4WttT8p7D34DvXRJBps_MZ5EtNq9N1A0y_P-iG=w408-h306-k-no'),
  ('ChIJCXUXVgA9LxgR2fXB-IKTI7k', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmcs9AILJmygUYa__WqVofNl3VvVNcw8d_f9xG8da4Eev-q8Dt0upU6T0vNDASezEliBctEeB0OJ-vOFEpPweDjMC2-yQONgnmG7WKpPE0RfpH6kGbJKlqpuyxEYrf3sXKkdjf1muObjB_v=w408-h306-k-no'),
  ('ChIJqzRWKR49LxgR3lMVEgVdRt4', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlHg_aJhE-kOUYBuna4nNtCvQ1h17j9QD0x0MCdOugk_wioFwL2dWILuIGIvrXHt4D3B-lmD1qURDUWJi3fTRttq-JsTcC36VNqVs2Rtmrp1DaWf_c-aFx5F5wHjoeWJxueKJSHKafQIWYZ=w408-h306-k-no'),
  ('ChIJ_0rDcXA_LxgR72FOcp-vuSs', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlLbvcvTYZZCU_xQeHmP1lSqJR1PiMjt3z-loJNt9s5r_X09i9xm9Df8JGmcqYXgmdiSANeWZ1LkOLScU94EgUvkTWRJ0DHa1D5ExjNcFF_rEeUYKOt28Lommtvk-tB3py8mOEEtfwUoGz6=w408-h544-k-no'),
  ('ChIJ1XT0KBgXLxgRFiJn3j1V-JU', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnS1QL1UKAxNEgFAxm_TG3SSsfxdT7lz2LawvcylEWEClEv4AKZxYLTbYIdcPPPgjZTAAmtj_TuHiuL7J-QrnvoLupvbKSGC3XK46VFk6WCwT7W9o9uVHFM8dgD3V5fgT1TCSc=w408-h306-k-no'),
  ('ChIJtZyfRJkQLxgRwxFlxG86K3Y', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkpxqrzuVLt2o5HiCIXltRIFUg7Acg_Awce1p19yxRoOvWf-kuyWqHjLZMLPXEzhsTdac4p9j1UfIV7O8UJlyhZgQ3I-hkrxgTqurF5GFIvZTrl96fpDNMjJHJoyBrgsHDjbDW2=w506-h240-k-no'),
  ('ChIJy_8XJNEXLxgRNkLfnx3oDyA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmgbs5q8R7NJMRhfmdNuLx0ZKFubplKz-DEhBo9QVEO1MdAgZnusoHg5b_jqZapUOU3UaGPckwqKcKVsmSXa5QOpc837kGl3V0oF7_VVl6_CDP-oBIlTyIIUhGCwyOdibOOjS3otbaF5_8=w408-h306-k-no'),
  ('ChIJoab-oJ4QLxgR6uck9Yx8Acs', 'https://lh3.googleusercontent.com/gps-proxy/ALd4DhHhHBBq_dq3QRydZykL5WfftvmvywnSW8CYw8dF5zOLvW_WO7EqttutHwGrluHn7HvE265zwsAp1mSF1LuUb07V4gGvrmpVmJNC7m9qobRJn2mQ5y65oepz91IkMzaM3wse7uDoshGwZ1PlrVF8GJ0f9Mc-Pm_azKZ6DYqD1CJ7Px-Xp2dFRML4-H5H5EkQBt_ALw=w408-h306-k-no'),
  ('ChIJnaYte649LxgR8pntju2-Ino', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWly_esEA8S5l60MXqMU3YlcxhrlILglb39U310E0V7D4XIk1yLU-atiNYNBcn3PFzNUYGUVowqvD1YLXSubOkt-WlVl6V3urIAsFg4zREQSxsuSTTaD2Nt6ew9zgbrD88rmIxSDNg=w426-h240-k-no'),
  ('ChIJvd_MWAAXLxgR0fIaUPWL6Hc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnIUN9aAcWoFz52HcHLkfrLJDZweyuZ9GxbB7BCF7MypuHkSMWV8x-CswMCbxkvGAAoi52p8GtghLZF9kWpikPuL4ygirZjV3x2x9px0yKFyVtJiJlQ0-TIlzy0HiovpVD4IO_vgFzaNmTd=w408-h544-k-no'),
  ('ChIJGXWmcho9LxgR9wR_3C1o4vc', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkyG0Dr71RLV3rmBP5w2XagajETJpCKMoSWbLmuf1UI_G7nWkjbhJqvqX98UsEZr8jtLGnGFjZI8yGJOI6dq19ah8cIe5mPNIBLtMQOIgHC1miJJodLQUJTK4GmgJe1XHzVqHtU=w408-h306-k-no'),
  ('ChIJTQSaUso9LxgRKvLpgXnXlUw', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=Gz11m6KNPymo77nXsqGc4Q&cb_client=search.gws-prod.gps&w=408&h=240&yaw=190.9383&pitch=0&thumbfov=100'),
  ('ChIJ4xbTJWM9LxgRVw0K6h9AH6E', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=j5bcORsPhFStcTHsrlJfsA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=241.25554&pitch=0&thumbfov=100'),
  ('ChIJ56kXLQAXLxgRWHGi-5qhihQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlmILTBhd3E33TQRCLZetZFoSQnxu8ftJMaNaYcbx2WxUP71KUvkCc1HTeV_76e3HykucRvmbapjb44kOMIK_FpBPdqx1msqTh8IZK3I3vhyKLuPAMrEVZ45tIx55X4jxaxWXVoONsG42z3=w408-h306-k-no'),
  ('ChIJU_v3Zv0XLxgRnIrl6LzUvgw', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn9dGmRRPotDy-BW7DRnX1z1TgLYKZRB1KAWstCdLuPKysSykW3McGmhXDdL0X1OS4f8wNzUqYbRF6OMasE3DEeJwy8clAL5rRtcaLqG0r03JPJ8GU6xu8-muYr5fYBMOpTniw=w408-h544-k-no'),
  ('ChIJscF9iyw9LxgRjkhAsSqXEhk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm1AfcaEj7xX56t4x82CA_bNIHbZqmH_djSDg2wBKBWcJ_uOk2J04KETakL-5U85clpV-Yt78qbca94TNd7bB6vzSbaqwuvGBkyqcdD78he4INl6MqwHFoMvXkvsa9EAndnZmw=w408-h544-k-no'),
  ('ChIJicu_AFYXLxgRg2IbXFQ4AmA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmKwuWuBfA4YGdowlIIyO45pXs0AwOqkKNieRdUbjzDBD7zBQkDnvl02KPKkS0sD1Xd5Hoyx4DYybQ0u9V0EOYjEsX6-yPppK9Nud6G7EMFBPa4wpq3Yb17gUY_IYXrCNOGu4Q=w408-h306-k-no'),
  ('ChIJrS15KYQ9LxgROlk1JaWHeww', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlkfFGh1FU-TyUk5Gw9MOJN_Xbo6PjhvVMM_bpbYKKUxFL9iHEhPTA6YHPCYav6p5T2Nne349yIU5wUroG5gnr9vEBnE3lDsXKDWs2hSRpTy032VpZnNKwDb_RrWXJOgDVuF2Yn6g=w425-h240-k-no'),
  ('ChIJ6fm1304XLxgRREcqzhi6cZk', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnF4yAXKDP9LbBmnusSGDc0Si9yEjbL36VOam5An9gepO4AaqQyRd-IMuowOdz1Gsb6H7GiIr9qQUPtF43lci1R1oFz4H3OcNGKqp_NKPJcWCakJIdbUAcTf1_m-bZXhHqW01RY=w408-h306-k-no'),
  ('ChIJ9fsTdgIXLxgRtt2QFZUnypM', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnZ0lOIfhtw1RBh-kzPPiyx6z51ggh4LFwF_cayTJLpO1XHLJ19ZIv6SIossPKU6SrkpZZ0vNbMtJl6LnaSPUWfqTlOES4D28vOHEToPSf9_6apOzla5aPQ7aPMs-0a8QpfWAO72M8QKiI=w408-h544-k-no'),
  ('ChIJMStCwjsXLxgRnMpgOhwzy4s', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnFUJQebruWHzaeW9wLnx56tKokeKpmU1P90P0UGiBW9HJQLufC2B_Z9eZv2k4MKRD_f9AkZsTTxBnNej3fhWmZWfFWPQXxvcPcLeaSv4G7zenQ_7GoC9XLWuSx16MwtU1Ldz598A=w408-h544-k-no'),
  ('ChIJxaDbujsRLxgR9YOjfYusyHA', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlrffwjracvLTBZ3Mt8wklzZRB1diF2e41JQx4YUh6YS6K4lsbYMoT8nTy3esGRtK-jWOd54FW9XNd7yfhsdDsPWRPJVab6eWCtPqVZicTFFqzdF_npgmVO9xL-lifK0WEFYYn6=w408-h272-k-no'),
  ('ChIJ0R0-UDA9LxgRMgABZs5sm2E', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl6olfB0RF5iBR-OYyBo67MUUjmJof8qfDmoGjinx3L305TouSE38EI9fDJe1_ZSYOGbfZYQ3OcjPJ62Jb04TDpVNot2AWSQ17bHPvZZ26qhENgXO742Uv85c-wNX0e_3JrEgIpqQ=w408-h272-k-no'),
  ('ChIJ7WHkAUoXLxgR9Z0DEsC3qCo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWldeZ8cV2mAGxbw8C_YyMV30lEIk3iDBj9Usk7NA78eguz-U18iIhKyq8Vi5obTQKeO6a-b45iVvYMdqxDkY-80VSXNVKa104weDhiLSATWdz_7GnmCprypdsYRPYtO9a26vyRTwg=w408-h272-k-no'),
  ('ChIJ6RzkG4IXLxgRWwSe4Tckrj0', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm1gj23QaPYsKheYUAr24T0X9fRIj-9VqDI7-h8qOM1O8IgsdkRuwN4x7DSyTu3WQfLOzfiLqVTVnQvUiBuivMnPTproGjtp56pcf40oA7wErwb746zxNV1AM-rwV0gVKX0znXu=w408-h306-k-no'),
  ('ChIJ_TMohhAXLxgRWZpFPyGiVbQ', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWljI7xIopI5fKDbiVaHGlQ_Z3U8ru1rEl3W_6TOgoHncN6y4FWQP0X2Vv6zZfPElm3Eoe0lolJgRSG98l3rRz5sGO_ne1cGa7L5e-N0rVroe9DU4okHJ7MSiQJ2BiUxgJr93ng7=w408-h305-k-no'),
  ('ChIJgx9oN8g9LxgR1YVqUSYTA24', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=v4QWjxL0fFfNQ9nM_PZhtA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=258.95538&pitch=0&thumbfov=100'),
  ('ChIJB3lfmfg9LxgRJ8XHjLzHASs', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmRPpXAtab4Acjz_YO1hkg0lA_E2gUF2FkRCSxA8JquJayWD2u4ZS6HWcKPE3_otzSchibxgydFq5j9QIjekZsrFXKGBLDAaBocznONVEy18ZKJpq80125ThDb94lZu0YvtzpOr=w408-h306-k-no'),
  ('ChIJdRIkic09LxgRIRslw4KU1jI', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlBvgISK1Z4RHvyZlldCuEXcdMCCGhjPyIZ3VmfZEmH0lNvGayZk7yrFldSfdNxoSsd80al3jsqBex_Yy0FX0a8fsxqHq_W1CpHr9W5ZS6pKQQ6a8pJeSnq3LD0vJ-oP5n0N7Uf=w408-h306-k-no'),
  ('ChIJS_aKVQAXLxgRV-AYwNH65eA', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=UlVDIMBH8Wg1-6kEFByLvg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=64.11312&pitch=0&thumbfov=100'),
  ('ChIJPVdjfwA9LxgRs0KYDChHg3E', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmPsBkJ_hpJAlsDFSxooe5jXui30gvzTN6Szk-BhsuiWJtWcqfB5YnL5LYcDbG4Uqk0vX-JmvCnY4XTwRy_tX54rWEViPi66mUY8yxcm116fWL-kVadtuvSi-nRguDC5jWaJ9BJ=w408-h306-k-no'),
  ('ChIJDyY_ahY9LxgRRlt_9LkVci8', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmFTbSz1JJp29A8L0B5FhAGowJQX2xkum1sL6aWiEKEvphOSa9QBoEgNfze3aRcHqfGeznWX1YN6mmgdKZwifd2VVvwK0ussgXQMRBIT25O5nru1nYOqxLdI9CUYBXcO1GPxxLid13ZGh-a=w408-h272-k-no')
) AS v(place_id, image_url) ON b.google_place_id = v.place_id
WHERE NOT EXISTS (
  SELECT 1 FROM business_images bi WHERE bi.business_id = b.id AND bi.is_cover = true
);
