-- =============================================================================
-- Kiambu Road Explorer — Migration 019 (part5of5)
-- Import newly-researched businesses along the Kiambu Road corridor (banks,
-- car dealers, auto services, construction, professional services, faith
-- community, real estate, home & garden, medical, education, malls/retail,
-- leisure, transport, security, membership clubs). All rows verified against
-- the live DB: zero google_place_id or slug collisions with existing data.
-- Run AFTER 018_dear_doctor.sql
-- =============================================================================

INSERT INTO businesses (name, slug, category_id, area_id, address_line, short_description, description, phone, website, google_maps_url, opening_hours_text, google_rating, google_review_count, status, verification_status, source_url, google_place_id)
VALUES
('Royal Umbrella Rent A Car', 'royal-umbrella-rent-a-car-05905ed1', '2451d8e2-a493-4792-ad9f-1a0070899e4c', NULL, 'Parklands, Nairobi', 'Car rental agency in Parklands, Nairobi.', 'Car rental agency. Located at Parklands, Nairobi. Contact for hours and services.', '+254743330251', 'https://royalumbrellacars.com/', 'https://www.google.com/maps/search/?api=1&query=Royal%20Umbrella%20Rent%20A%20Car&query_place_id=ChIJ8_-VdBkXLxgRPXpzF1Y-vrk', NULL, 4.9, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Royal%20Umbrella%20Rent%20A%20Car&query_place_id=ChIJ8_-VdBkXLxgRPXpzF1Y-vrk', 'ChIJ8_-VdBkXLxgRPXpzF1Y-vrk'),
('Rarity Rent A Car', 'rarity-rent-a-car-f4ab3dd0', '2451d8e2-a493-4792-ad9f-1a0070899e4c', NULL, 'The Trio Complex, Nairobi', 'Car rental agency in The Trio Complex, Nairobi.', 'Car rental agency. Located at The Trio Complex, Nairobi. Contact for hours and services.', '+254714633463', 'http://www.raritycars.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Rarity%20Rent%20A%20Car&query_place_id=ChIJm_dfgTYXLxgRMLnAiKJlTi4', NULL, 4.9, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Rarity%20Rent%20A%20Car&query_place_id=ChIJm_dfgTYXLxgRMLnAiKJlTi4', 'ChIJm_dfgTYXLxgRMLnAiKJlTi4'),
('Kitlio Executive Transfers', 'kitlio-executive-transfers-e539e2b0', '2451d8e2-a493-4792-ad9f-1a0070899e4c', NULL, 'Madonna House, Westlands Rd', 'Airport transfers, Car rental in Madonna House, Westlands Rd.', 'Airport transfers, Car rental. Located at Madonna House, Westlands Rd. Contact for hours and services.', '+254716070064', 'https://kitlioexecutive.com/', 'https://www.google.com/maps/search/?api=1&query=Kitlio%20Executive%20Transfers&query_place_id=ChIJWxHbFV4RLxgRrfRkl-wZsrA', NULL, 4.9, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Kitlio%20Executive%20Transfers&query_place_id=ChIJWxHbFV4RLxgRrfRkl-wZsrA', 'ChIJWxHbFV4RLxgRrfRkl-wZsrA'),
('Electric Fences Kenya', 'electric-fences-kenya-f69a2498', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', 'e89f2c90-4edf-4683-9b79-cdd09f8173e1', 'Kiambu Rd, Nairobi', 'Security system installation, Electric fences in Kiambu Rd, Nairobi.', 'Security system installation, Electric fences. Located at Kiambu Rd, Nairobi. Contact for hours and services.', '+254722708034', 'http://www.electricfences.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Electric%20Fences%20Kenya&query_place_id=ChIJcWKgSIYlLxgRXjwZ9cDbCDI', NULL, 4.3, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Electric%20Fences%20Kenya&query_place_id=ChIJcWKgSIYlLxgRXjwZ9cDbCDI', 'ChIJcWKgSIYlLxgRXjwZ9cDbCDI'),
('Searite Security', 'searite-security-1effab70', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', 'e89f2c90-4edf-4683-9b79-cdd09f8173e1', 'Kiambu, Kenya', 'Security guard service in Kiambu, Kenya.', 'Security guard service. Located at Kiambu, Kenya. Contact for hours and services.', '+254722692699', 'http://www.searitesecurity.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Searite%20Security&query_place_id=ChIJ_4chbl48LxgRMtLoiMfZYGE', NULL, 3.6, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Searite%20Security&query_place_id=ChIJ_4chbl48LxgRMtLoiMfZYGE', 'ChIJ_4chbl48LxgRMtLoiMfZYGE'),
('Guard Lens Security Systems', 'guard-lens-security-systems-d3045dfa', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'CCTV, Access control, Electric fence in Nairobi, Kenya.', 'CCTV, Access control, Electric fence. Located at Nairobi, Kenya. Contact for hours and services.', '+254799633695', NULL, 'https://www.google.com/maps/search/?api=1&query=Guard%20Lens%20Security%20Systems&query_place_id=ChIJB0T53gMZLxgR1-GAWc2stGk', NULL, 5.0, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Guard%20Lens%20Security%20Systems&query_place_id=ChIJB0T53gMZLxgR1-GAWc2stGk', 'ChIJB0T53gMZLxgR1-GAWc2stGk'),
('Pro-Alarms Security Ltd', 'pro-alarms-security-ltd-c216f9c5', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'Security guards, Systems in Nairobi, Kenya.', 'Security guards, Systems. Located at Nairobi, Kenya. Contact for hours and services.', '+254720116088', 'http://proalarmtec.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Pro-Alarms%20Security%20Ltd&query_place_id=ChIJhdhU7uwVLxgR2HfNpN56-NI', NULL, 4.3, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Pro-Alarms%20Security%20Ltd&query_place_id=ChIJhdhU7uwVLxgR2HfNpN56-NI', 'ChIJhdhU7uwVLxgR2HfNpN56-NI'),
('Realtech Security Systems', 'realtech-security-systems-21845df4', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'CCTV, Fire alarms, Fencing in Nairobi, Kenya.', 'CCTV, Fire alarms, Fencing. Located at Nairobi, Kenya. Contact for hours and services.', '+254716076315', NULL, 'https://www.google.com/maps/search/?api=1&query=Realtech%20Security%20Systems&query_place_id=ChIJU--oa7ARLxgRh3gf7jLk_RM', NULL, 4.8, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Realtech%20Security%20Systems&query_place_id=ChIJU--oa7ARLxgRh3gf7jLk_RM', 'ChIJU--oa7ARLxgRh3gf7jLk_RM'),
('D&B Security Services', 'd-b-security-services-f6f94f4a', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'CCTV, Fire alarms in Nairobi, Kenya.', 'CCTV, Fire alarms. Located at Nairobi, Kenya. Contact for hours and services.', '+254700598164', NULL, 'https://www.google.com/maps/search/?api=1&query=D&B%20Security%20Services&query_place_id=ChIJb9KoFMkbLxgRcT0gaf5GREo', NULL, 4.9, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=D&B%20Security%20Services&query_place_id=ChIJb9KoFMkbLxgRcT0gaf5GREo', 'ChIJb9KoFMkbLxgRcT0gaf5GREo'),
('Security Systems International Ltd', 'security-systems-international-ltd-4f14cdf9', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'Security systems, Guard services in Nairobi, Kenya.', 'Security systems, Guard services. Located at Nairobi, Kenya. Contact for hours and services.', '+254780233251', 'http://www.securitysystemsintltd.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Security%20Systems%20International%20Ltd&query_place_id=ChIJza4weKARLxgRYn5LJ9cHuJI', NULL, 4.4, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Security%20Systems%20International%20Ltd&query_place_id=ChIJza4weKARLxgRYn5LJ9cHuJI', 'ChIJza4weKARLxgRYn5LJ9cHuJI'),
('Mighty Solutions', 'mighty-solutions-5f2f5e6a', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'CCTV, Burglar alarms in Nairobi, Kenya.', 'CCTV, Burglar alarms. Located at Nairobi, Kenya. Contact for hours and services.', '+254719773257', 'http://www.mightysolutions.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Mighty%20Solutions&query_place_id=ChIJVVVV6DEXLxgRNvwXqqIjyg4', NULL, 4.8, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Mighty%20Solutions&query_place_id=ChIJVVVV6DEXLxgRNvwXqqIjyg4', 'ChIJVVVV6DEXLxgRNvwXqqIjyg4'),
('Realicon Digital Solutions Kenya Ltd', 'realicon-digital-solutions-kenya-ltd-a4c0973e', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', 'e89f2c90-4edf-4683-9b79-cdd09f8173e1', 'Kenneth Matiba Rd, Ruiru', 'Security systems, Home automation in Kenneth Matiba Rd, Ruiru.', 'Security systems, Home automation. Located at Kenneth Matiba Rd, Ruiru. Contact for hours and services.', '+254711354180', 'https://realicon.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Realicon%20Digital%20Solutions%20Kenya%20Ltd&query_place_id=ChIJwWfT4rcRLxgR6rwVWfxMG_4', NULL, 4.9, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Realicon%20Digital%20Solutions%20Kenya%20Ltd&query_place_id=ChIJwWfT4rcRLxgR6rwVWfxMG_4', 'ChIJwWfT4rcRLxgR6rwVWfxMG_4'),
('Haven Secure Solutions Ltd', 'haven-secure-solutions-ltd-76f3f34e', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', 'e89f2c90-4edf-4683-9b79-cdd09f8173e1', 'White Angle, Kenneth Matiba Rd', 'Security installation, Fire protection in White Angle, Kenneth Matiba Rd.', 'Security installation, Fire protection. Located at White Angle, Kenneth Matiba Rd. Contact for hours and services.', '+254726076004', 'https://havensecuresolutions.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Haven%20Secure%20Solutions%20Ltd&query_place_id=ChIJqcbpKBARLxgRUk9apsg12VY', NULL, 4.9, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Haven%20Secure%20Solutions%20Ltd&query_place_id=ChIJqcbpKBARLxgRUk9apsg12VY', 'ChIJqcbpKBARLxgRUk9apsg12VY'),
('Informed Systems Ltd', 'informed-systems-ltd-b4561c1d', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Ojijo Plaza, Parklands', 'Security systems, Access control in Ojijo Plaza, Parklands.', 'Security systems, Access control. Located at Ojijo Plaza, Parklands. Contact for hours and services.', '+254794764203', 'https://www.informedsystemsltd.com/', 'https://www.google.com/maps/search/?api=1&query=Informed%20Systems%20Ltd&query_place_id=ChIJp3ECKyYRLxgRBfzY4ztwLhc', NULL, 4.8, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Informed%20Systems%20Ltd&query_place_id=ChIJp3ECKyYRLxgRBfzY4ztwLhc', 'ChIJp3ECKyYRLxgRBfzY4ztwLhc'),
('Boardtac Solutions', 'boardtac-solutions-396da4bd', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'CCTV, Security systems in Nairobi, Kenya.', 'CCTV, Security systems. Located at Nairobi, Kenya. Contact for hours and services.', '+254113670045', 'https://www.boardtac.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Boardtac%20Solutions&query_place_id=ChIJm_IF7YEVLxgRvxnU5cDbKvM', NULL, 5.0, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Boardtac%20Solutions&query_place_id=ChIJm_IF7YEVLxgRvxnU5cDbKvM', 'ChIJm_IF7YEVLxgRvxnU5cDbKvM'),
('Debrazz Security Systems', 'debrazz-security-systems-d28be9e8', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'Security systems, CCTV in Nairobi, Kenya.', 'Security systems, CCTV. Located at Nairobi, Kenya. Contact for hours and services.', '+254725522048', 'https://debrazzsecuritysystems.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Debrazz%20Security%20Systems&query_place_id=ChIJxREJkVPJK2gRrAUp9uT7hYY', NULL, 4.8, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Debrazz%20Security%20Systems&query_place_id=ChIJxREJkVPJK2gRrAUp9uT7hYY', 'ChIJxREJkVPJK2gRrAUp9uT7hYY'),
('Naibuni Systems Company', 'naibuni-systems-company-8ad8a50b', 'eb67ee78-be20-4839-90d7-e3e2efa177e1', NULL, 'Nairobi, Kenya', 'Fire fighting equipment, Security in Nairobi, Kenya.', 'Fire fighting equipment, Security. Located at Nairobi, Kenya. Contact for hours and services.', '+254717140369', 'https://naibunisystems.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Naibuni%20Systems%20Company&query_place_id=ChIJMdCAQzMRLxgRhwKsiK_JMq0', NULL, 4.9, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Naibuni%20Systems%20Company&query_place_id=ChIJMdCAQzMRLxgRhwKsiK_JMq0', 'ChIJMdCAQzMRLxgRhwKsiK_JMq0'),
('Gigiri Social Club', 'gigiri-social-club-a0de1ffd', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', '552b4a27-8340-4959-9953-d17995353d38', 'Gigiri Rd, Nairobi', 'Sports club in Gigiri Rd, Nairobi.', 'Sports club. Located at Gigiri Rd, Nairobi. Contact for hours and services.', '+254798400900', 'https://gigirisocialclub.com/', 'https://www.google.com/maps/search/?api=1&query=Gigiri%20Social%20Club&query_place_id=ChIJzWdk89UXLxgRr69RoRVbIKw', NULL, 4.7, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Gigiri%20Social%20Club&query_place_id=ChIJzWdk89UXLxgRr69RoRVbIKw', 'ChIJzWdk89UXLxgRr69RoRVbIKw'),
('Ballpoint Social Club', 'ballpoint-social-club-738a6e44', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', '552b4a27-8340-4959-9953-d17995353d38', 'Village Market, Limuru Rd', 'Board game club, Restaurant, Bar in Village Market, Limuru Rd.', 'Board game club, Restaurant, Bar. Located at Village Market, Limuru Rd. Contact for hours and services.', '+254207122476', NULL, 'https://www.google.com/maps/search/?api=1&query=Ballpoint%20Social%20Club&query_place_id=ChIJKeA9joYXLxgRSOkqloBf_hc', NULL, 4.2, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Ballpoint%20Social%20Club&query_place_id=ChIJKeA9joYXLxgRSOkqloBf_hc', 'ChIJKeA9joYXLxgRSOkqloBf_hc'),
('Stima Members Club', 'stima-members-club-8e50bf04', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', NULL, 'Nairobi, Kenya', 'Sports club in Nairobi, Kenya.', 'Sports club. Located at Nairobi, Kenya. Contact for hours and services.', '+254711031000', NULL, 'https://www.google.com/maps/search/?api=1&query=Stima%20Members%20Club&query_place_id=ChIJywD9Q4UWLxgRwM4pQWKQqiI', NULL, 4.1, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Stima%20Members%20Club&query_place_id=ChIJywD9Q4UWLxgRwM4pQWKQqiI', 'ChIJywD9Q4UWLxgRwM4pQWKQqiI'),
('Muthaiga Country Club', 'muthaiga-country-club-502ef88c', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', '808c3a37-b090-4a44-90a0-a4792c20150e', '30 Muthaiga Rd, Nairobi', 'Country club in 30 Muthaiga Rd, Nairobi.', 'Country club. Located at 30 Muthaiga Rd, Nairobi. Contact for hours and services.', '+254207229000', 'http://www.mcc.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Muthaiga%20Country%20Club&query_place_id=ChIJaVQzF-kWLxgRiZdpWVQ2AsI', NULL, 4.6, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Muthaiga%20Country%20Club&query_place_id=ChIJaVQzF-kWLxgRiZdpWVQ2AsI', 'ChIJaVQzF-kWLxgRiZdpWVQ2AsI'),
('Premier Club', 'premier-club-0d9a29a5', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', NULL, 'Nairobi, Kenya', 'Club in Nairobi, Kenya.', 'Club. Located at Nairobi, Kenya. Contact for hours and services.', '+254206763331', NULL, 'https://www.google.com/maps/search/?api=1&query=Premier%20Club&query_place_id=ChIJkcTATt8WLxgRoLV3dkY1QBg', NULL, 4.3, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Premier%20Club&query_place_id=ChIJkcTATt8WLxgRoLV3dkY1QBg', 'ChIJkcTATt8WLxgRoLV3dkY1QBg'),
('The Goan Gymkhana', 'the-goan-gymkhana-df1ae80f', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', NULL, 'Nairobi, Kenya', 'Sports club in Nairobi, Kenya.', 'Sports club. Located at Nairobi, Kenya. Contact for hours and services.', '+254720526523', NULL, 'https://www.google.com/maps/search/?api=1&query=The%20Goan%20Gymkhana&query_place_id=ChIJMaBbhC8XLxgRBk9NQ9W4xXg', NULL, 4.3, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=The%20Goan%20Gymkhana&query_place_id=ChIJMaBbhC8XLxgRBk9NQ9W4xXg', 'ChIJMaBbhC8XLxgRBk9NQ9W4xXg'),
('SD Padel Gigiri Courtyard', 'sd-padel-gigiri-courtyard-b3d137bc', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', '552b4a27-8340-4959-9953-d17995353d38', 'Gigiri Ln, Nairobi', 'Sports club, Padel in Gigiri Ln, Nairobi.', 'Sports club, Padel. Located at Gigiri Ln, Nairobi. Contact for hours and services.', '+254741012345', NULL, 'https://www.google.com/maps/search/?api=1&query=SD%20Padel%20Gigiri%20Courtyard&query_place_id=ChIJw9zWRqkXLxgRsn0giTq0gQg', NULL, 2.8, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=SD%20Padel%20Gigiri%20Courtyard&query_place_id=ChIJw9zWRqkXLxgRsn0giTq0gQg', 'ChIJw9zWRqkXLxgRsn0giTq0gQg'),
('Ruiru Sports Club', 'ruiru-sports-club-cd8c7240', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', 'e89f2c90-4edf-4683-9b79-cdd09f8173e1', 'Thika Rd, Ruiru', 'Sports club in Thika Rd, Ruiru.', 'Sports club. Located at Thika Rd, Ruiru. Contact for hours and services.', '+254758380139', 'http://ruirusportsclub.co.ke/', 'https://www.google.com/maps/search/?api=1&query=Ruiru%20Sports%20Club&query_place_id=ChIJ_VeHahtHLxgROUQ-mQsKjn4', NULL, 4.2, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Ruiru%20Sports%20Club&query_place_id=ChIJ_VeHahtHLxgROUQ-mQsKjn4', 'ChIJ_VeHahtHLxgROUQ-mQsKjn4'),
('Parklands Sports Club', 'parklands-sports-club-af371d12', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', NULL, 'Parklands Rd, Nairobi', 'Sports complex in Parklands Rd, Nairobi.', 'Sports complex. Located at Parklands Rd, Nairobi. Contact for hours and services.', '+254203752917', 'http://www.parklandssportsclub.org/', 'https://www.google.com/maps/search/?api=1&query=Parklands%20Sports%20Club&query_place_id=ChIJCw1PvzwXLxgRoXWWQXlwApI', NULL, 4.4, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Parklands%20Sports%20Club&query_place_id=ChIJCw1PvzwXLxgRoXWWQXlwApI', 'ChIJCw1PvzwXLxgRoXWWQXlwApI'),
('Wadi Degla Club - Kiambu', 'wadi-degla-club-kiambu-1cc94670', '9f2ecb56-8d49-4e9f-b927-6beffdd6ea2e', 'e89f2c90-4edf-4683-9b79-cdd09f8173e1', 'Kasarini Rd, Kiambu', 'Sports club in Kasarini Rd, Kiambu.', 'Sports club. Located at Kasarini Rd, Kiambu. Contact for hours and services.', '+254792888888', 'https://www.wdclubsafrica.com/', 'https://www.google.com/maps/search/?api=1&query=Wadi%20Degla%20Club%20-%20Kiambu&query_place_id=ChIJCe0srzg9LxgRvADBjB69-eM', NULL, 4.6, NULL, 'published', 'unverified', 'https://www.google.com/maps/search/?api=1&query=Wadi%20Degla%20Club%20-%20Kiambu&query_place_id=ChIJCe0srzg9LxgRvADBjB69-eM', 'ChIJCe0srzg9LxgRvADBjB69-eM');
